### ISSUE TITLE
ultisnips show errors when enter the <tab> key in .js file

### ISSUE THREAD

**Issue by glenlance** [SirVer/ultisnips#1064]
when I edit a *.js file , I cannot press the <tab> key, otherwise It will show the errors below:

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 710, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 665, in _do_snippet
    self._visual_content, parent, start, end)
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 477, in launch
    snippet_instance.update_textobjects(_vim.buf)
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done, buf):
  File "/home/glen/.vim/pack/myplugins/start/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 273, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'javascript_snippets'

Executed snippet code:
  1 > from javascript_snippets import (
  2   	semi, space_before_function_paren, keyword_spacing
  3   )

**Comment by glenlance** [comment]
I already test the *.php *.go *.html filetypes . it all show normal ,only the js file show errors.
I think this situation should envolve with the system envirment , so I didn't use the docker.

**Comment by glenlance** [comment]
I solved this proble by recompling my vim
