### ISSUE TITLE
Ultisnips and LaTeX don't play nice together

### ISSUE THREAD

**Issue by BreadyX** [SirVer/ultisnips#1075]
**Expected behavior:**
Ultisnips should parse the snippets and give me the snippet when I type the trigger word in a .tex file.

**Actual behavior:**
Throws an error with this backtrace:
```
Traceback (most recent call last):
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper 
        return func(self, *args, **kwds)                                            
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _track_change
         self._try_expand(autotrigger_only=True)                                     
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 694, in _try_expand
         snippets = self._snips(before, False, autotrigger_only)                     
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 574, in _snips
         source.ensure(filetypes)                                                    
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 32, in ensure
         self._load_snippets_for(ft)                                                 
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 54, in _load_snippets_for
         self._parse_snippets(ft, fn)                                                
    File "/home/breadyx/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 69, in _parse_snippets
         raise SnippetSyntaxError(filename, line_index, msg)                         
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '\\\\begin\\{itemize\\}' in .config/nvim/snippets/tex.snippets:4
```

**Steps to reproduce**
1. Open a `.tex` file with NeoVim (`:echo &ft` gives `tex`)
2. Enter insert mode and type the first letter of the snippet (in this case "i")
3. Error pops up in another buffer

MWE of **init.vim**:
```
call plug#begin($HOME . '/.local/share/nvim/plugged')
Plug 'SirVer/ultisnips'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

" ultisnips
" Snippets directory
let g:UltiSnipsSnippetDirectories=[ $HOME . '/.config/nvim/snippets' ]

" Trigger configuration
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-f>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"
```
MWE of **tex.snippets**
```
snippet itemize "\begin{itemize}"
\\begin\{itemize\}
	\\item ${0:item}
\\end\{itemize\}
endsnippet
```
-----
- **Operating System**:  Fedora 29
- **NeoVim Version**:  NVIM v0.3.3
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 3.7.3 (default, Mar 27 2019, 13:41:07)[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
- **Docker repo/vimrc**: [full init.vim](https://github.com/BreadyX/dotfiles/tree/master/.config/nvim)

**Comment by quantizzed** [comment]
This is likely caused by the fact that your snippet file is in the _"snippets"_ directory, whereas the UltiSnips documentation clearly says that

> Note that directories named "snippets" arereserved for snipMate snippets and cannot be used.
