### ISSUE TITLE
The snippets content that did not converge

### ISSUE THREAD

**Issue by zhuosongz** [SirVer/ultisnips#1088]
I am using the following snippet: 

```
global !p
bracklist = {}
bracklist['('] = ['(',')']
bracklist['['] = ['[',']']
bracklist['{'] = ['\{','\}']
bracklist['|'] = ['\lvert ',"\\rvert"]
bracklist['?'] = ['\lVert ',"\\rVert"]

biglist = {}
# biglist['a'] = ['', '']
biglist['b'] = ["\\bigl", "\\bigr"]
biglist['B'] = ['\Bigl', '\Bigr']
biglist['bb'] = ["\\biggl", "\\biggr"]
biglist['BB'] = ['\Biggl', '\Biggr']
endglobal


snippet '([bB]{1,2})([\(\[\{|?])' "Description" wrA
`!p snip.rv = biglist[match.group(1)][0]``!p snip.rv = bracklist[match.group(2)][0]`${1:Type the equation here}`!p snip.rv = biglist[match.group(1)][1]``!p snip.rv = bracklist[match.group(2)][1]`$0
endsnippet

snippet '([\(\[\{|?])([\(\[\{|?])' "Description" wrA
`!p snip.rv = bracklist[match.group(2)][0]`${1:Type the equation here}`!p snip.rv = bracklist[match.group(2)][1]`$0
endsnippet
```
The expected behavior is: 
```
b{  -->  \bigl\{${1:Type the equation here}\bigr\}
{{  --> \{${1:Type the equation here}\}
```
However, sometimes, there are some unexpected behavior: For example: 
```		
		{{y -->	\{y\}\}\}\}\}\}\}\}\}\}\}
		
```
Here, `{{` gives `\{${1:Type the equation here}\}`, and then I want to input the equation, start with `y`. Therefore, the expected behavior is 
```
{{y --> \{y<cursor>\}
```

Moreover, the following error appears: 
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 339, in _cursor_moved
    self._active_snippets[0].update_textobjects(_vim.buf)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 85, in update_textobjects
    'The snippets content did not converge: Check for Cyclic '
RuntimeError: The snippets content did not converge: Check for Cyclic dependencies or random strings in your snippet. You can use 'if not snip.c' to make sure to only expand random output once.
```

**Comment by SirVer** [comment]
Only a hunch, but if you execute this snippet a few times in a row (i.e. without hitting the `$0` of one of the snippets), the outer snippets will still be active and your regex will still execute for them, i.e. they are still active. This will work better if you make `${1:Type the equation here}` to `${0:Type the equation here}`, so that your smart snippet immediately exits when you arrive in the middle.
