### ISSUE TITLE
RecursionError while expanding snippet

### ISSUE THREAD

**Issue by chuugar** [SirVer/ultisnips#1175]
I created a LaTeX snippet to take a screenshot and add it within my .tex file.
For the following explanation, here's the tree of my LaTeX projects :

     .
    ├──  img
    │   ├──  img1.png
    │   ├──  img2.png
    │   ├──  ...
    ├──  sshot
    │   ├──  sshot202001081854.png
    │   ├──  sshot202001082131.png
    │   └──  ...
    ├──  tex
    │   ├──  subfolder1
    │   │   ├──  file1.tex
    │   │   └──  file2.tex
    │   ├──  subfolder2
    │   │   ├──  file1.tex
    │   │   └──  file2.tex
    │   ├──  ...
    │   │   └──  ...
    │   ├──  file01.tex
    │   ├──  file02.tex
    │   ├──  ...
    └──  master.tex

`incsshot` take a screenshot with `maim` and add it in the folder `sshot` of my LaTeX project.
`_rec_finder` is a recursive function that find the path of the `sshot` folder.

     def incsshot(path, c, t):
        def _recursive_finder(path, target):
            _path = pathlib.Path(path)
            _target = pathlib.Path(target)
            x = []

            if _path.is_file():
                _path = _path.parent

            for dirf in _path.iterdir():
                x.append(dirf.name)

            if target in x:
                return _path.joinpath(target)

            if _path.name == "latex":
                return
            else:
                return _recursive_finder(_path.parent, target)

        _sshot_path = "sshot"  # folder where screenshots are saved

        _prefix = "sshot"
        sshot_time = time.strftime('%Y%m%d%H%M')
        _ext = ".png"
        sshot_fn = _prefix + sshot_time + _ext  # filename of the screenshot

        # Find and resolve _sshot_path, return pathlib.Path object
        sshot_fpath = _recursive_finder(path, _sshot_path)

        if sshot_fpath.is_dir():
            sshot_path = sshot_fpath.joinpath(sshot_fn) # full path for filename

        if c == "":
            run(["maim", "-s", "-b", "10", sshot_path])
            return """{{{}}}\nlabel{{fig:{}}}""".format(sshot_path, t)

    snippet shot "Call and add screenshot" b
    \begin{figure}[h]
        \begin{center}
            \includegraphics[scale=${1:1}]`!p snip.rv = incsshot(path, snip.c, t[2])`
        \end{center}
        \caption{${2}}
    \end{figure}
    ${0}
    endsnippet

It works as expected with iPython3, but when it's running in Vim I've got the following error :

    An error occured. This is either a bug in UltiSnips or a bug in a
    snippet definition. If you think this is a bug, please report it to
    https://github.com/SirVer/ultisnips/issues/new
    Please read and follow:
    https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

    Following is the full stack trace:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/pathlib.py", line 697, in __str__
        return self._str
    AttributeError: _str

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
        return func(self, *args, **kwds)
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 176, in expand_or_jump
        rv = self._try_expand()
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 795, in _try_expand
        self._do_snippet(snippet, before)
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 748, in _do_snippet
        text_before, self._visual_content, parent, start, end
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 488, in launch
        snippet_instance.update_textobjects(vim_helper.buf)
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 93, in update_textobjects
        if obj._update(done, buf):
      File "/home/chuugar/.config/vim/pack/git/start/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 268, in _update
        exec(code, self._locals)  # pylint:disable=exec-used
      File "<string>", line 1, in <module>
      File "<string>", line 45, in incsshot
      File "<string>", line 37, in _rec_finder
      File "<string>", line 37, in _rec_finder
      File "<string>", line 37, in _rec_finder
      [Previous line repeated 976 more times]
      File "<string>", line 27, in _rec_finder
      File "/usr/lib/python3.7/pathlib.py", line 1365, in is_file
        return S_ISREG(self.stat().st_mode)
      File "/usr/lib/python3.7/pathlib.py", line 1161, in stat
        return self._accessor.stat(self)
      File "/usr/lib/python3.7/pathlib.py", line 704, in __fspath__
        return str(self)
      File "/usr/lib/python3.7/pathlib.py", line 700, in __str__
        self._parts) or '.'
      File "/usr/lib/python3.7/pathlib.py", line 681, in _format_parsed_parts
        return cls._flavour.join(parts)
    RecursionError: maximum recursion depth exceeded while calling a Python object

    Executed snippet code:
      1   snip.rv = incsshot(path, snip.c, t[2])

**Comment by chuugar** [comment]
I found out that that `path` as described at [Ultisnips-Python](https://github.com/SirVer/ultisnips/blob/96026a4df27899b9e4029dd3b2977ad2ed819caf/doc/UltiSnips.txt#L852) doesn't return the fullpath of the file curently edited, but only the name of this file.
So if I change `!p snip.rv = incsshot(path, snip.c, t[2])` to `!p snip.rv = incsshot(pathlib.Path(path).resolve(), snip.c, t[2])` it works as expected
