### ISSUE TITLE
UltiSnipsEdit will not start

### ISSUE THREAD

**Issue by Msrgit** [SirVer/ultisnips#1190]
**Expected behavior:**
UltiSnipsEdit and UltiSnipsEdit! should start

**Actual behavior:**129d33fc34a72ced857f3cfb72ff10caf10f0020
UltiSnipsEdit does not start. This traceback produced:

Error detected while processing function UltiSnips#Edit:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 851, in _file_to_edit
    _get_potential_snippet_filenames_to_edit(snippet_dir, filetypes)
  File "/home/mark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 94, in _get_potential_snippet_filenames_to_edit
    ft_snippets_files = find_snippet_files(ft, snippet_dir)
  File "/home/mark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/ulti_snips.py", line 26, in find_snippet_files
    directory = os.path.expanduser(directory)
  File "/usr/lib/python3.5/posixpath.py", line 228, in expanduser
    if not path.startswith(tilde):
AttributeError: 'PosixPath' object has no attribute 'startswith'

**Steps to reproduce**

.vimrc directives only:

"
"UltiSnips
"
let g:UltiSnipsUsePythonVersion=3
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

1. :UltiSnipEdit
2.
3.

-----

- **Linux Mint 18.3**: 
- **VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 27 2020 23:43:58)
Included patches: 1-326:**: 
- **UltiSnips Version**: 
129d33fc34a72ced857f3cfb72ff10caf10f0020
- **Python inside Vim**:
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Python 3.5 is not supported since it is very old. Python 3.6 is the first to be supported. Time to upgrade?
