### ISSUE TITLE
您好，这是怎么回事，如何解决

### ISSUE THREAD

**Issue by zhimujun** [SirVer/ultisnips#1194]
An error occured. This is either a bug in UltiSnips or a bug in a                                          
snippet definition. If you think this is a bug, please report it to                                        
https://github.com/SirVer/ultisnips/issues/new                                                             
Please read and follow:                                                                                    
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs                           
                                                                                                           
Following is the full stack trace:                                                                         
Traceback (most recent call last):                                                                    File"/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper return func(self, *args, **kwds)                                                                       
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 896, in _track_change self._try_expand(autotrigger_only=True)                                                                
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 788, in _try_expand snippets = self._snips(before, False, autotrigger_only)                                                
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips source.ensure(filetypes)                                                                               
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure self._load_snippets_for(ft)                                                                            
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for self._parse_snippets(ft, fn)                                                                           
  File "/home/chen/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets raise SnippetSyntaxError(filename, line_index, msg)                                                    
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '\t{' in ~/.vim/snippets/c.snippets:67       
                                                                                                                                   

**Steps to reproduce**

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
> UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '\t{' in ~/.vim/snippets/c.snippets:67

Seems your snippets are invalid.
