### ISSUE TITLE
pynvim.api.common.NvimError: Index out of bounds

### ISSUE THREAD

**Issue by YaLTeR** [SirVer/ultisnips#1206]
**Expected behavior:**
No error.

**Actual behavior:**
```
Traceback (most recent call last):
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 416, in _cursor_moved
    self._active_snippets[0].update_textobjects(vim_helper.buf)
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 93, in update_textobjects
    if obj._update(done, buf):
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 253, in _update
    ct = self.current_text
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/base.py", line 113, in current_text
    return vim_helper.buf[self._start.line][self._start.col : self._end.col]
  File "/home/yalter/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/vim_helper.py", line 22, in __getitem__
    return vim.current.buffer[idx]
  File "/usr/lib/python3.7/site-packages/pynvim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/usr/lib/python3.7/site-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Index out of bounds
```

**Steps to reproduce**

1. Open an empty file index.html
2. `html<Tab><Esc>ggcGhtml<Tab><Esc>ggcG`

-----

- **Operating System**: Fedora 31
- **Vim Version**: NVIM v0.4.3
- **UltiSnips Version**: ee31ea1c7d08ced8577120b4c1d55c5a05351a75
- **Python inside Vim**: 3.7.6
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Can't repo. What is the `<html>` snippet in this case?
