### ISSUE TITLE
Error Detected while processing 

### ISSUE THREAD

**Issue by Raoul555** [SirVer/ultisnips#1209]
**Expected behavior:**

Open a text file in Vim and entering insert mode allows me to type in characters normally.

**Actual behavior:**

Since installing UltiSnips, every keystroke entered in insert mode results in the following error text:

```
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
```

An additional ENTER prompts the following:

```Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
```

**Steps to reproduce**

Invoke vim via a `git commit --amend`
Switch to edit mode, and type any text.
At first keystroke press while in editing mode, the error appears.

-----

- **OS**:

Debian 10

- **Vim Version**:

IM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +digraphs          +lispindent        +persistent_undo   +textobjects
+arabic            +dnd               +listcmds          +postscript        +textprop
+autocmd           -ebcdic            +localmap          +printer           +timers
+autochdir         +emacs_tags        +lua               +profile           +title
-autoservername    +eval              +menu              -python            +toolbar
+balloon_eval      +ex_extra          +mksession         +python3           +user_commands
+balloon_eval_term +extra_search      +modify_fname      +quickfix          +vartabs
+browse            +farsi             +mouse             +reltime           +vertsplit
++builtin_terms    +file_in_path      +mouseshape        +rightleft         +virtualedit
+byte_offset       +find_in_path      +mouse_dec         +ruby              +visual
+channel           +float             +mouse_gpm         +scrollbind        +visualextra
+cindent           +folding           -mouse_jsbterm     +signs             +viminfo
+clientserver      -footer            +mouse_netterm     +smartindent       +vreplace
+clipboard         +fork()            +mouse_sgr         +startuptime       +wildignore
+cmdline_compl     +gettext           -mouse_sysmouse    +statusline        +wildmenu
+cmdline_hist      -hangul_input      +mouse_urxvt       -sun_workshop      +windows
+cmdline_info      +iconv             +mouse_xterm       +syntax            +writebackup
+comments          +insert_expand     +multi_byte        +tag_binary        +X11
+conceal           +job               +multi_lang        +tag_old_static    -xfontset
+cryptv            +jumplist          -mzscheme          -tag_any_white     +xim
+cscope            +keymap            +netbeans_intg     +tcl               +xpm
+cursorbind        +lambda            +num64             +termguicolors     +xsmp_interact
+cursorshape       +langmap           +packages          +terminal          +xterm_clipboard
+dialog_con_gui    +libcall           +path_extra        +terminfo          -xterm_save
+diff              +linebreak         +perl              +termresponse
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/l
ib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pang
o-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0
-I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/inc
lude/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/inclu
de -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-pref
ix-map=/build/vim-4Pursk/vim-8.1.0875=. -fstack-protector-strong -Wformat -Werror=format-security -U_FOR
TIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-
z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcai
ro -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetyp
e -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl
 -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl
/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython
3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lrub
y-2.5 -lpthread -lgmp -ldl -lcrypt -lm

- **UltiSnips Version**:

? (How to get that? I'm using vim-plug to get UtilSnips)

- **Python inside Vim**:

3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0]

- **Docker repo/vimrc**:

N/A

**Comment by 8bittree** [comment]
Regarding the Ultisnips version, try checking the directory to which vim-plug is installing plugins. By default I think it's `~/.vim/plugged`, but you can specify a different directory when calling `plug#begin()`. Whichever directory it is, you should be able to pull the commit id from the ultisnips repo clone within.

**Comment by Raoul555** [comment]
Updated with my Ultisnips version

**Comment by nnop** [comment]
met the same issue.

- vim 8.2
- python 3.7.2

**Comment by weizhou-chaojixx** [comment]
met the same issue.

- vim 8.2

- python 3.6

**Comment by SirVer** [comment]
Thanks for the report. The `NameError: name 'UltiSnips_Manager' is not defined` revealed by hitting Enter is the actual error - it tells us the UltiSnips Python module failed to import on this Vim. Everything else (the "empty Traceback" on the first prompt) is Vim splitting the multi-line `:python3` error across "Press ENTER" prompts.

The underlying "import failed, now every keystroke surfaces a stack trace" story is tracked in #1237, which has the most discussion of the right user experience (silent fallback vs. one-time warning). Let's keep that conversation in one place.

Closing as a duplicate of #1237. If you can capture the import-time error itself (e.g. `:py3 import UltiSnips` from a fresh Vim, before any keystroke) please post it on #1237.
