### ISSUE TITLE
SnippetSyntaxError: Invalid line '    '

### ISSUE THREAD

**Issue by winkee01** [SirVer/ultisnips#1210]
since Ultisnips supports snipMate also, so I tried this:

~/.vim/snippets/cpp.snippets

```
snippet ustd
    using namespace std;
```

**<font color='red'>Error(while typing u insert mode):</font>**

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 896, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 788, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips
    source.ensure(filetypes)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/winkee/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 71, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '    using namespace std;' in ~/.vim/snippets/cpp.snippets:2
```

**more**

I have tried some more, all prompt errors, like:

(1) same error

```
snippet ustd
    are you ok?
```

(2) same error

```
snippet prv
    private
```

(3) replace to nothing

```
snippet inci
    #include <iostream>
```

version: vim 8.2

**Comment by lacygoill** [comment]
Make sure that the snippet is indented with a literal tab character.

Start Vim like this:

    vim -Nu NONE +'set list' ~/.vim/snippets/cpp.snippets

And you should see this:

    snippet ustd$
    ^Iusing namespace std;$
    ^^
    tab character

If you don't see `^I`, run this command while on the `using namespace std;` line:

    :s/\s\+/\t/ | update

**Comment by winkee01** [comment]
Now it works! Thank you for the precious help.
