### ISSUE TITLE
Mouse click while viewing snippets list triggers stack trace

### ISSUE THREAD

**Issue by systemmonkey42** [SirVer/ultisnips#1226]
**Expected behavior:**
Click outside snippets list should cancel.

**Actual behavior:**
Click outside snippets list generates `IndexError: list index out of range`

**Steps to reproduce**

1.  open file with active snippets.
  ensure mouse is enabled (I use `set mouse=ar`)
2. type a letter (to filter snippets list)
3. press ListSnippets hotkey to list matching snippets
4. Click anywhere in VIM dispay but not on a line containing a snippet.

There is also an __off by one__ issue when clicking on snippets in the list.
* Clicking on the top snippet cancels
* Clicking on any snippet select the one on the previous line
* Clicking on the `Type number ...` prompt selects the last displayed snippet
* Clicking on a snippet while `-- More --` is display simply advances the list instead of selecting the snippet.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 253, in list_snippets
    snippet = _ask_snippets(snippets)
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 64, in _ask_snippets
    return _ask_user(snippets, display)
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 41, in _ask_user
    return a[rv - 1]
IndexError: list index out of range
```

-----

- **Operating System**:
Ubuntu 18.04
- **Vim Version**: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453

- **UltiSnips Version**:
e35158de39767ef887a4d1e2a83786576d5a8477
- **Python inside Vim**:
:py import sys; print(sys.version)`
Unavailable
`:py3 import sys; print(sys.version)'
3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0]
- **Docker repo/vimrc**:
If needed I can publish a docker image.

**Comment by SirVer** [comment]
An easy fix, finally done after 6 years.
