### ISSUE TITLE
erred when access attribute snip.p.start in global snippets

### ISSUE THREAD

**Issue by haolian9** [SirVer/ultisnips#1231]
**Expected behavior:**

can access attributes of snip.p.start.col in global snippets

**Actual behavior:**

raised exception

**Steps to reproduce**

1. python.snippets like that:
```
global !p
def with_indent(inp, start):
    return ">> {}".format(start.col)  # errs
    # some other cases
    # return ">> {}".format(start[0]) # errs
    # return ">> {}".format(type(start)) # works
endglobal

snippet echo
${1:param}`!p snip.rv = with_indent(t[1], snip.p.start)`
endsnippet
```
2. in a python file, `echo<TAB>`
3. erred

-----
- **Operating System**: centos 7
- **Vim Version**: nvim 0.4.2
- **UltiSnips Version**: master 96026a
- **Python inside Vim**: python 3.6.8

full error output:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 185, in expand_or_jump
    rv = self._try_expand()
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 804, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 757, in _do_snippet
    text_before, self._visual_content, parent, start, end
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 488, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 93, in update_textobjects
    if obj._update(done, buf):
  File "/home/someone/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 268, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 1, in <module>
  File "<string>", line 18, in with_indent
AttributeError: 'int' object has no attribute 'col'

Executed snippet code:
  1   snip.rv = with_indent(t[1], snip.p.start)
```

**Comment by haolian9** [comment]
I wanted to get indent of placeholder, since this way wasnt work, I figured out another way: `snip._initial_indent`
