### ISSUE TITLE
I get an error when trying to edit snippets

### ISSUE THREAD

**Issue by espijuanjo** [SirVer/ultisnips#1235]
I get this error:
Error detected while processing function UltiSnips#Edit:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/myuser/.vim/bundle/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 852, in _file_to_edit
    _get_potential_snippet_filenames_to_edit(snippet_dir, filetypes)
  File "/home/myuser/.vim/bundle/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 98, in _get_potential_snippet_filenames_to_edit
    potentials.add(os.path.join(snippet_dir, ft + ".snippets"))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'

When I try to do :UltiSnipsEdit.

**Expected behavior:**
I expect to have a vertical split to edit the snippets

**Actual behavior:**
It crashes with the error above

**Steps to reproduce**

I just installed using VundleInstall. I have installed ultisnips-php too and try to edit snippets... the plugin works good. It's only the edition what is not working...

This is my related .vimrc:

let g:UltiSnipsExpandTrigger="\<tab\>"
let g:UltiSnipsJumpForwardTrigger="\<c-b\>"
let g:UltiSnipsJumpBackwardTrigger="\<c-z\>"
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetsDir = "/home/myuser/.vim/bundle/ultisnips-php/UltiSnips/"

-----

- **Operating System**: 
Debian 9
- **Vim Version**: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
- **UltiSnips Version**: 
3.2
- **Python inside Vim**: 
\<none\>/3.5.3
- **Docker repo/vimrc**:

**Comment by espijuanjo** [comment]
I just found my python is too old... sorry...
