### ISSUE TITLE
Invalid line

### ISSUE THREAD

**Issue by TornaxO7** [SirVer/ultisnips#1248]
My `~/.vim/snippets/c.snippets`:
```snippets
snippet ok "test" b
#define test 0
endsnippet
```
When I'm entering `insert mode` than this pops up:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 897, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 789, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 669, in _snips
    source.ensure(filetypes)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line 'endsnippet' in ~/.vim/snippets/c.snippets:3
```
The releveant part of `~/.vim/vimrc`:
```vim
" ultisnips
source ~/.vim/plugins/ultisnips.vim
```
`~/.vim/plugins/ultisnips.vim`:
```vim
" snippets directory
let g:UltiSnipsSnippetDirectories =  ['~/.vim/snippets']
```
I'm a little bit confused...
I'm using `coc-snippets` too, but uninstalling didn't help the error still pops up and removing the `endsnippet` line didn't help too, because than this pops up:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 897, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 789, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 669, in _snips
    source.ensure(filetypes)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/tornax/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Missing 'endsnippet' for 'ok' in ~/.vim/snippets/c.snippets:2
```
What am I doing wrong?

**Comment by TornaxO7** [comment]
It works now (although I don't know why)

**Comment by SirVer** [comment]
@TornaxO7 @Nealium You are likely using `~/.vim/snippets` for files that use UltiSnips syntax. That does not work, since `snippets` is reserved for VimSnips snippets - all files in there are expected to be vimsnip. Use a different name for your snippet directory and you should be good.

**Comment by Nealium** [comment]
@SirVer Yep!! That's exactly what it was. smh and now that you mention it I specifically remember reading **don't use snippets as the folder name** somewhere

Thanks for wasting your time on me lol
