### ISSUE TITLE
I am getting this issue in Windows 10...Neovim

### ISSUE THREAD

**Issue by anixn** [SirVer/ultisnips#1302]
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 896, in _track_change
    self._try_expand(autotrigger_only=True)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 789, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 669, in _snips
    source.ensure(filetypes)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet\source\file\base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet\source\file\base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "C:\Users\Ankit Deshmukh\AppData\Local\nvim\plugged\ultisnips\pythonx\UltiSnips\snippet\source\file\base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '" Now you can define you snippets' in c:usersankit deshmukhappdatalocal
vimpluggedvim-snippetsultisnips	ex.snippets:60

**Comment by LiterallyJohnny** [comment]
Well, you haven't really provided us any information. We can't help you if you post an error and nothing else. With the information you have provided, the most I can suggest is to reinstall UltiSnips.

**Comment by raprocks** [comment]
@anixn have you edited or made a new snippets file? if so remove the file and then try again because it seems like a syntax error for the snippet in the snippets file.

**Comment by SirVer** [comment]
> UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '" Now you can define you snippets' in c:usersankit deshmukhappdatalocal

This makes me believe you are not using UltiSnips snippet syntax. Closing for lack of information, I will reopen when more information is provided.
