### ISSUE TITLE
Getting the snippet result from `UltiSnips#ExpandSnippetOrJump()` and the sucess separately

### ISSUE THREAD

**Issue by thorlucas** [SirVer/ultisnips#1305]
I'm trying to define a function in neovim lua. This function is mapped to a keystroke and executes an expression that runs a lua function which:

- If the pop up menu is visible, then navigate through it (CoC stuff), by returning "<C-n>"
- Otherwise, call the UltiSnips#ExpandSnippetOrJump()
    - If this result is > 0, then return '<C-R>=[the snippet result]<CR>'
    - Otherwise, return '<Tab>'
 
Ok, so let's simplify. At first I tried this:

```lua
function _G.plugins.coc.tab_completion()
	if pumvisible() then
		return map.esc('<C-n>')
	else
		return map.esc('<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>')
	end
end

...

map.keymap('i', '<Tab>',   'v:lua.plugins.coc.tab_completion()',       { expr = true })
```

This works fine, except it's impossible to type a regular tab character now. So let's try to rectify that. If, after running `UltiSnips#ExpandSnippetOrJump()`, the `g:ulti_expand_or_jump_res` is 0, we just type a Tab. Otherwise, we will do the `<C-R>=...`

```lua
function _G.plugins.coc.tab_completion()
	if pumvisible() then
		return map.esc('<C-n>')
	else
		vim.cmd [[call UltiSnips#ExpandSnippetOrJump()]]
		if vim.g.ulti_expand_or_jump_res > 0 then
			return map.esc('<C-R>=[what goes here?]<CR>')
		else
			return map.esc('<Tab>')
		end
	end
end
```

Really, this doesn't work. I think calling `UltiSnips#ExpandSnippetOrJump()` actually tries to do something sneaky and return the text directly and nvim doesn't like that:

```
E5108: Error executing lua /Users/thorcorreia/.config/nvim/lua/plugins/_lsp/_coc.lua:20: Vim(return):Error invoking 'python_ex
ecute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line
18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 187, i
n expand_or_jump
    rv = self._try_expand()
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 807, i
n _try_expand
    self._do_snippet(snippet, before)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 759, i
n _do_snippet
    snippet_instance = snippet.launch(
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", lin
e 487, in launch
    snippet_instance.replace_initial_text(vim_helper.buf)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py
", line 61, in replace_initial_text
    _place_initial_text(self)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py
", line 56, in _place_initial_text
    obj.overwrite_with_initial_text(buf)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/text_objects/base.py", line 131,
 in overwrite_with_initial_text
    self.overwrite(buf, self._initial_text)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/text_objects/base.py", line 146,
 in overwrite
    self._end = _replace_text(buf, self._start, self._end, gtext)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/text_objects/base.py", line 34,
in _replace_text
    buf[start.line : end.line + 1] = new_lines
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/vim_helper.py", line 25, in __se
titem__
    vim.current.buffer[idx] = text
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/api/buffer.py", line 65, in __setitem__
    return self.request('nvim_buf_set_lines', start, end, False, lines)
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: E523: Not allowed here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line
52, in wrapper
    vim_helper.new_scratch_buffer(msg)
  File "/Users/thorcorreia/.local/share/nvim/site/pack/packer/opt/ultisnips/pythonx/UltiSnips/vim_helper.py", line 155, in new
_scratch_buffer
    vim.command("botright new")
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/thorcorreia/Library/Python/3.9/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(new):E523: Not allowed here
```

When there is no snippet to return, the function works fine.

So what really needs to happen is there needs to be a way to call `UltiSnips#ExpandSnippetOrJump()` and save the result rather than trying to "return it directly", or whatever black magic UltiSnips is doing.

**Comment by Antonio-Bennett** [comment]
@thorlucas Hi I think we are having the same Ideas. I would love to use honza snippets since there is a wide variety and they come preinstalled for a lot of languages. I'm coming from vim-vsnip which doesn't support it but the original code I had is 

```
 _G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-n>"
    elseif vim.fn.call("vsnip#available", {1}) == 1 then
      return t "<Plug>(vsnip-expand-or-jump)"
    elseif check_back_space() then
      return t "<Tab>"
    else
      return t "<Plug>(completion_smart_tab)"
    end
  end
  _G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-p>"
    elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
      return t "<Plug>(vsnip-jump-prev)"
    else
      return t "<Plug>(completion_smart_s_tab)"
    end
  end
```
I thought this would map to this code below with your contribution but it doesn't seem to work any ideas?
```
_G.tab_complete = function()                                                                                            if vim.fn.pumvisible() == 1 then
      return t "<C-n>"
    elseif vim.api.nvim_eval([[ UltiSnips#CanExpandSnippet() ]]) == 1 then
      return vim.fn['UltiSnips#ExpandSnippetOrJump']()
    elseif check_back_space() then
      return t "<Tab>"
    else
      return t "<Plug>(completion_smart_tab)"
    end
  end
  _G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-p>"
    elseif vim.api.nvim_eval([[ UltiSnips#CanJumpBackwards() ]]) == 1 then
      return vim.fn['UltiSnips#JumpBackwards']()
    else
      return t "<Plug>(completion_smart_s_tab)"
    end
  end
```

**Comment by MetriC-DT** [comment]
Here's my way of doing something similar. I set it up so that if I don't have something in the popup selected, try an expansion or jump. However, I'm running into an issue where *nested* snippets breaks (am unable to jump out of the outer snippet)
```lua
-- escape termcodes properly
local t = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

-- check back spaces
local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end

-- run through checking ultisnips viability. Returns fallthrough if fails
local trigger_ultisnips_fwd = function(fallthrough)
    if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
        return t([[<C-R>=UltiSnips#ExpandSnippet()<CR>]])
    elseif vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
        return t([[<C-R>=UltiSnips#JumpForwards()<CR>]])
    else
        return t(fallthrough)
    end
end

-- run through s-tab options too
local trigger_ultisnips_bak = function(fallthrough)
    if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
        return t([[<C-R>=UltiSnips#JumpBackwards()<CR>]])
    else
        return t(fallthrough)
    end
end

-- tab completion for compe
_G.tab_complete = function()
    -- if popup visible and has a value selected, go down
    if vim.fn.pumvisible() ~= 0 and vim.fn.complete_info()["selected"] ~= -1 then
        return t("<C-N>")
    -- if popup is visible, but no value selected, attempt snippet expand
    elseif vim.fn.pumvisible() ~= 0 then
        return trigger_ultisnips_fwd("<C-N>")
    elseif check_back_space() then
        return t("<TAB>")
    else
        return trigger_ultisnips_fwd("<TAB>")
    end
end

-- s-tab completion for compe
_G.s_tab_complete = function()
    if vim.fn.pumvisible() ~= 0 and vim.fn.complete_info()["selected"] ~= -1 then
        return t("<C-P>")
    -- if popup is visible, but no value selected, attempt snippet previous jump
    elseif vim.fn.pumvisible() ~= 0 then
        return trigger_ultisnips_bak("<C-P>")
    else
        return trigger_ultisnips_bak("<S-TAB>")
    end
end
```

**Comment by SirVer** [comment]
Quick recap for anyone landing here, since the thread answers the question but doesn't say *why* the original pattern failed:

The error you hit (`E523: Not allowed here`) is not from UltiSnips per se - it's Nvim's textlock guard refusing buffer mutations while the screen is in the middle of evaluating an expression. `UltiSnips#ExpandSnippetOrJump()` mutates the buffer (that's its whole job), so calling it directly from inside a Lua function that runs in an `<expr>` mapping or from a `:return` expression always trips this guard. The classic `<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>` mapping works precisely because it schedules the mutation as a separate insert-register evaluation, which runs outside the locked context.

For Lua callers, the right separation is the predicate trio plus a key-feeding step:

- `UltiSnips#CanExpandSnippet()` / `UltiSnips#CanJumpForwards()` / `UltiSnips#CanJumpBackwards()` are read-only and safe to call from any expression context.
- Once you've decided which action to take, return the `<C-R>=...<CR>` sequence (or feed it via `nvim_feedkeys` / `nvim_replace_termcodes`) instead of calling the function directly. dericktseng's snippet above is exactly this pattern and works correctly.

The predicates were already in UltiSnips when this issue was filed; the gap was that they were undocumented as the answer to this specific failure mode. They are now covered by a regression test so they don't quietly drift.
