### ISSUE TITLE
problem while installing ultisnips

### ISSUE THREAD

**Issue by santiFerra** [SirVer/ultisnips#1324]
i've installed by using vim-plug and this error appeared:
Following is the full stack trace:
Traceback (most recent call last):
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 200, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 671, in _snips
    source.ensure(filetypes)
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/santino_ferra/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line 'for (int i = 0; i < 5; i++) {' in ~/.vim/snippets/cpp.snippets:3

**Comment by TornaxO7** [comment]
What's in your `vimrc`/`init.vim`?

**Comment by SirVer** [comment]
This probably timed out.
