### ISSUE TITLE
SnippetSyntaxError: Invalid line 'global !p'

### ISSUE THREAD

**Issue by edunfelt** [SirVer/ultisnips#1342]
**Expected behavior:** 
Entering insert mode and allow typing as usual, trigger snippets as defined.

**Actual behavior:**
After changing the location of the .vim directory and .vimrc (not sure if related since I'm also on a new install) suddenly this error message appears:
```
Traceback (most recent call last):
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py",     line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 933, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 794, in _try_expand
    before, snippets = self._can_expand(autotrigger_only)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 790, in _can_expand
    return before, self._snips(before, False, autotrigger_only)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 671, in _snips
    source.ensure(filetypes)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py",  line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py",  line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/edun/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py",  line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line 'global !p' in .config/vim/snippets/tex.snippets:1
```
I have not edited the file containing the snippets, so nothing seems to be amiss there.

**Steps to reproduce**

Full `.vimrc` can be found [here](https://github.com/edunfelt/dots/blob/main/.config/vim/vimrc), but the relevant parts for UltiSnips are: 
```
set runtimepath+=~/.config/vim,~/.config/vim/after
{...}
Plugin 'SirVer/ultisnips'

let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories = ["$HOME/.config/vim/snippets"]
```

and first line of snippet definition (also available in full above)
```
global !p
texMathZones = ['texMathZone'+x for x in ['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E', 'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS', 'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W', 'X', 'Y', 'Z']]
```

1. Enter vim.
2. Switch to insert mode.
3. Type any character.

-----

- **Operating System**:  Arch linux
- **Vim Version**:  `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 26 2021 00:21:09)
Included patches: 1-2653`
- **UltiSnips Version**:  `d4330c4 - (HEAD -> master, origin/master, origin/HEAD) Fix race condition in checking vim startup. (#1331)`
- **Python inside Vim**: <!-- e.g. 2.7.14 / 3.6.5. If unsure run inside vim:
                              `:py import sys; print(sys.version)` and
                              `:py3 import sys; print(sys.version)' --> `3.9.2 [GCC 10.2.0]`

**Comment by SirVer** [comment]
`snippets` is a reserved directory for vim-snippets snippets. See for example #703 and many other reports like this. Please change `let g:UltiSnipsSnippetDirectories = ["$HOME/.config/vim/snippets"]` to using something else but `snippets`.
