### ISSUE TITLE
Can't use python with UltiSnips

### ISSUE THREAD

**Issue by L1szt** [SirVer/ultisnips#1367]
I want to use UltiSnips with latex and am following [this](https://castel.dev/post/lecture-notes-1/) popular post. I'm using [this](https://github.com/gillescastel/latex-snippets/blob/master/tex.snippets) `tex.snippets` file whereby the following error occurs when I try to start typing:
```
Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 933, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 794, in _try_expand
    before, snippets = self._can_expand(autotrigger_only)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 790, in _can_expand
    return before, self._snips(before, False, autotrigger_only)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 671, in _snips
    source.ensure(filetypes)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/me/.local/share/nvim/site/pack/packer/start/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line 'global !p' in ~/.config/nvim/snippets/tex.snippets:1
```
Apparently there is a difficulty with the python section, but python3 works just fine for my neovim. 
This section is probably causing the issue:
```python
global !p
def math():	return vim.eval('vimtex#syntax#in_mathzone()') == '1'
def comment(): 	return vim.eval('vimtex#syntax#in_comment()') == '1'
def env(name):	[x,y] = vim.eval("vimtex#env#is_inside('" + name + "')") return x != '0' and y != '0'
endglobal
```

What could the reason for this problem be?

**Comment by SirVer** [comment]
The problem is that you use `snippets` as your snippet directory. This is reserved for snipMate snippets and UltiSnips will try to parse any files in such a directory as snipMate snippet. See https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L523 for details.

**Comment by L1szt** [comment]
Wow, thanks for the fast answer! After renaming I no longer get the error but the snippets still don't seem to work...

**Comment by SirVer** [comment]
@L1szt Can you open a new issue with all of your snippets and your minimal vimrc so we can have a look at the snippets problem?

**Comment by L1szt** [comment]
Never mind, I could fix the internal problems (my setup is a bit complicated since I'm transitioning to neovim powered by lua which involves a lot of new stuff). Thanks a lot for your quick answer and for the nice extension!
