### ISSUE TITLE
"filename" expanded failed in vimscript

### ISSUE THREAD

**Issue by jayli** [SirVer/ultisnips#1397]
I got thiese err logs:

```
An error occured. This is either a bug in UltiSnips or a bug in a                                                                                                                             
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 187, in expand_or_jump
    rv = self._try_expand()
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 810, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _do_snippet
    snippet_instance = snippet.launch(
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 488, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 96, in update_textobjects
    if obj._update(done, buf):
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/viml_code.py", line 20, in _update
    self.overwrite(buf, vim_helper.eval(self._code))
  File "/Users/bachi/.vim/bundle/ultisnips/pythonx/UltiSnips/vim_helper.py", line 122, in eval
    return vim.eval(text)
vim.error: Vim:E117: Unknown function: Filename            
```

**Comment by SirVer** [comment]
No idea what you are doing, what snippet you are trying to expand, what your installation is. Somewhere in your snippet it seems to be using `Filename` which is not a Vim function? If you need more help please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.

**Comment by shahms** [comment]
I encounter this issue when using the `cl` snippet from `~/.vim/snippets/cpp.snippets`.  I believe this is an issue with the SnipMate support/installation. I'm honestly not sure where that file or directory came from at this point.  So not an UltiSnips bug, but might help for future triage :-)
