### ISSUE TITLE
NameError: name 'complete' is not defined

### ISSUE THREAD

**Issue by TamaMcGlinn** [SirVer/ultisnips#1445]
I was trying to follow your UltiSnips screencast, but at 3:47 you describe a completion snippet which does not work.

**Expected behavior:**
Completion of the strings provided.

**Actual behavior:**
This error is thrown:

```
 Following is the full stack trace:
 Traceback (most recent call last):
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
     return func(self, *args, **kwds)
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 173, in expand
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 810, in _try_expand
     snippet = snippets[0]
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _do_snippet
     ("D", start.line, start.col, snippet.matched),
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 489, in launch
     snippet_instance.replace_initial_text(vim_helper.buf)
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 100, in update_textobjects
     if obj._update(done, buf):
   File "/home/s1000586/.vim/plugged/UltiSnips/pythonx/UltiSnips/text_objects/python_code.py", line 268, in _update
     exec(code, self._locals)  # pylint:disable=exec-used
   File "<string>", line 1, in <module>
 NameError: name 'complete' is not defined

 Executed snippet code:
   1 > snip.rv=complete(t[1], ['new', 'incomplete', 'invalid'])
```

**Steps to reproduce**

Create e.g. mail.snippets with this in it:

```
snippet st "Status" b
  status $1`!p snip.rv=complete(t[1], ['new', 'incomplete', 'invalid'])`
endsnippet
```

1. Open a file and set the filetype to mail: `set ft=mail`.
2. Type in st
3. Press [enter] to activate the snippet

-----

- **Operating System**: Ubuntu 20.04
- **Vim Version**: Neovim 0.6
- **UltiSnips Version**: [current origin/master](https://github.com/SirVer/ultisnips/commit/ca21d30c7a72e0e18ad95f25ded5a5f820052685)
- **Python inside Vim**: 3.8.10

**Comment by TamaMcGlinn** [comment]
I am such an idiot. You explain how that 'complete' function is defined right afterwards in the video. I guess since you already had it defined in your vimrc, you were able to demonstrate before showing the code.
