### ISSUE TITLE
Command 'UltiSnipsEdit' raises an error.

### ISSUE THREAD

**Issue by azubirif** [SirVer/ultisnips#1561]
**Expected behavior:**
Be able to edit my snippets.

**Actual behavior:**
The following error is being raised:
```
AttributeError: type object 'PathFinder' has no attribute 'find_module'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "", line 1, in <module>
SystemError: initialization of vim raised unreported exception
línea   11:
AttributeError: type object 'PathFinder' has no attribute 'find_module'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "", line 1, in <module>
  File "C:\Users\aleja\vimfiles\plugged\ultisnips\pythonx\UltiSnips\__init__.py", line 6, in <module>
    from UltiSnips.snippet_manager import UltiSnips_Manager
  File "C:\Users\aleja\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 11, in <mod
ule>
    import vim
SystemError: initialization of vim raised unreported exception
Se ha detectado un error al procesar function UltiSnips#Edit:
línea    6:
Traceback (most recent call last):
  File "", line 1, in <module>
NameError: name 'vim' is not defined
```

**Steps to reproduce**
1. Install UltiSnips through vim-plug.
2. Open Vim and run `:UltiSnipsEdit`
Here is the only thing related to UltiSnips in my `.vimrc`:
```
call plug#begin()
Plug 'sirver/ultisnips'
...
call plug#end()
```

-----

- **Operating System**: Windows 10 
- **Vim Version**:
VIM - Vi IMproved 9.1 (2024 Jan 02, compilado Jan  2 2024 23:53:44)
Versión de 64 bits para consola de MS-Windows
- **UltiSnips Version**: 3.2 
- **Python inside Vim**: 3.13.1 
- **Docker repo/vimrc**: [https://github.com/SirVer/ultisnips/releases/tag/3.2](url)

**Comment by Konfekt** [comment]
This is using a Scoop install of Vim and Python3

**Comment by Konfekt** [comment]
Out of reflex, I wanted to suggest to update to `vim-nightly` in Scoop; however that package seems gone and one's stuck with `9.1.0`

**Comment by zackb2020** [comment]
This looks like due to **find_module** being removed from Python 3.13.
https://docs.python.org/release/3.13.0/whatsnew/changelog.html
[gh-98040](https://github.com/python/cpython/issues/98040): Remove more deprecated importlib APIs: find_loader(), find_module(), importlib.abc.Finder, pkgutil.ImpImporter, pkgutil.ImpLoader.

**Comment by bothyhead** [comment]
I got the same thing updating to Python 3.13.1 yesterday. I downgraded to 3.12.8, and Ultisnips is working again.

**Comment by SirVer** [comment]
Uh... seems like python 3.13 support needs some love. I try to squeeze this in soonish. thanks for the report!

**Comment by SirVer** [comment]
Though I am not sure if we can do anything about this besides telling people to update their python to a version after the linked commit.

**Comment by SirVer** [comment]
Alrighty, I spent some time on this today and indeed there is nothing Ultisnips can do about this problem. It is indeed not possible to use Vim with `python3` before 9.1.0417; see here: https://github.com/vim/vim/issues/14776

In #1567 I updated the test suite to test only with py13 after this Vim version, so at least the development is not affected, but it does not help users running into this problem. For them the solution is to upgrade to a Vim >= 9.1.0417.

**Comment by curbe454** [comment]
Same error.
My `C:\python13` is installed when installing `nodejs` and I don't want to install another version.
And the `vim` that installed by scoop in my computer can't be updated.
```shell
$ scoop update vim
vim: 9.1.0 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```
But there's a nightly-version in `versions` bucket.
```shell
$ scoop search vim
Results from local buckets...

Name             Version           Source   Binaries
----             -------           ------   --------
gow              0.8.0             main     vim.exe
neovim           0.11.2            main
psutils          0.2023.06.28      main     vimtutor.ps1
vim              9.1.0             main
vimtutor         0.2018.07.25      main
fvim             0.3.543           extras
goneovim         0.6.14            extras
lunarvim         1.3.0             extras
neovim-qt        0.2.19            extras
wsl-terminal     0.9.2             extras   vim.exe
goneovim-nightly 20250617          versions
neovim-nightly   0.12.0-640        versions
vim-nightly      9.1.1471          versions
vim-tux          9.1.1466_20250618 versions
```
So I uninstalled the `vim` to install the `vim-nightly` to solve this problem.
