### ISSUE TITLE
Error: Invalid line, raised on a custom snippet

### ISSUE THREAD

**Issue by pgilad** [SirVer/ultisnips#224]
I'm getting the following error:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet_manager.py", line 48, in wrapper
    return func(self, *args, **kwds)
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet_manager.py", line 123, in expand_or_jump
    rv = self._try_expand()
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet_manager.py", line 457, in _try_expand
    snippets = self._snips(before, False)
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet_manager.py", line 397, in _snips
    for snippet in provider.get_snippets(filetypes, before, possible):
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet\source\file\_base.py", line 36, in get_snippets
    self._ensure_loaded(ft, set())
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet\source\file\_base.py", line 55, in _ensure_loaded
    self._load_snippets_for(ft)
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet\source\file\_base.py", line 79, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "C:/Users/user/vimfiles/bundle/ultisnips/pythonx\UltiSnips\snippet\source\file\_base.py", line 95, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line 'var ${1:functionName} = function (${2:arguments}) {' in Usersuser.dotfilessnippetsjavascript.snippets:2
```

This is caused by a custom js snippet:

```
snippet vf "var functionName = function (params)"
var ${1:functionName} = function (${2:arguments}) {
    ${VISUAL}$0
};
endsnippet
```

This has worked before until a recent update today... Appreciate the help

**Comment by megalithic** [comment]
:+1:
