### ISSUE TITLE
UltiSnips scan the 'snippets' folder in vim-snippets for snippets

### ISSUE THREAD

**Issue by UncleBill** [SirVer/ultisnips#233]
I do set

``` viml
let g:UltiSnipsSnippetDirectories=["UltiSnips"]
```

even set absolute path

``` viml
let g:UltiSnipsSnippetDirectories=["~/.vim/bundle/vim-snippets/UltiSnips"]
```

,But US still searchs snippets in **"snippets"** folder.

I got

```
Anr error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 48, in wrapper
    return func(self, *args, **kwds)
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 136, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 412, in _snips
    for snippet in source.get_snippets(filetypes, before, possible):
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 36, in get_snippets
    self._ensure_loaded(ft, set())
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 55, in _ensure_loaded
    self._load_snippets_for(ft)
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 79, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/unclebill/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 95, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '    var ${1};${2}' in .vim/bundle/vim-snippets/snippets/javascript/javascript.snippets:3
```

What do I miss? Thanks.

**Comment by wanchaol** [comment]
Is this issue fixed already? I use "UltiSnips" and "Vim-snippets" in C++, when I expand "inc", it always give me two options which are annoying (it also load snippets folder, not the Ultisnips folder). Could anyone give me a hint how to fix this?

**Comment by ches** [comment]
@wanchaol I don't think that's an UltiSnips fault *per se*, there is no UltiSnips snippet defined for "inc" in the vim-snippets repo. The issue is that the snipMate snippets define two snippets for "inc", [one in the cpp file][1] and [one in the c file][2] which cpp extends—they probably shouldn't do that, but regardless, I would solve it by creating your own copy of the "inc" snippet in your `~/.vim/UltiSnips/c.snippets`, then UltiSnips will favor it and not prompt you.

[1]: https://github.com/honza/vim-snippets/blob/d285c86221e917d13c6cbf89f347627ea9fe1796/snippets/cpp.snippets#L6
[2]: https://github.com/honza/vim-snippets/blob/d285c86221e917d13c6cbf89f347627ea9fe1796/snippets/c.snippets#L19

**Comment by arnaudlamy** [comment]
I have the same issue, with my python snippets, I changed the default folder, when I run UltiSnipsEdit it opens the right file but when I do c-tab I have the default list without my new ones ( "t" & "todo").

My vimrc (.vimrc.local 'cause I'm using spf13 conf):

```
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsSnippetsDir = "~/config/UltiSnips"
let g:UltiSnipsSnippetDirectories=["~/config/UltiSnips"]
```

~/config/UltiSnips/python.snippets:

```
snippet todo "TODO reminder" b
    # TODO(`echo $USER`): ${1:desc} `!v strftime("%c")`
endsnippet

snippet t "A simple test"
    Test
endsnippet
```

**Comment by wanchaol** [comment]
@ches Yes you are right! Thanks for the recommendation! I have fixed that.
