### ISSUE TITLE
when I press tab before \ 

### ISSUE THREAD

**Issue by primitivorm** [SirVer/ultisnips#430]
I have an issue when press tab before "\" view [cursor_here] in my _vimrc, e.g.

set guifont=Consola_Mono:h10,
      [cursor_here]\Consola_Mono:h10,
            \Consolas_for_Powerline_FixedD:h10

Following is the full stack trace:
Traceback (most recent call last):
  File "..\pythonx\UltiSnips\snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "..\pythonx\UltiSnips\snippet_manager.py", line 144, in expand_or_jump
    rv = self._try_expand()
  File "..\pythonx\UltiSnips\snippet_manager.py", line 574, in _try_expand
    snippets = self._snips(before, False)
  File "..\pythonx\UltiSnips\snippet_manager.py", line 489, in _snips
    source.ensure(filetypes)
  File "..\pythonx\UltiSnips\snippet\source\file\_base.py", line 42, in ensure
    if self._needs_update(ft):
  File "..\pythonx\UltiSnips\snippet\source\file\_base.py", line 56, in _needs_update
    existing_files = self._get_all_snippet_files_for(ft)
  File "..\pythonx\UltiSnips\snippet\source\file\ultisnips.py", line 151, in _get_all_snippet_files_for
    return find_all_snippet_files(ft)
  File "..\pythonx\UltiSnips\snippet\source\file\ultisnips.py", line 45, in find_all_snippet_files
    "You have 'snippets' in UltiSnipsSnippetDirectories. This "
RuntimeError: You have 'snippets' in UltiSnipsSnippetDirectories. This directory is reserved for snipMate snippets. Use another directory for UltiSnips snippets.

**Comment by SirVer** [comment]
~~~
RuntimeError: You have 'snippets' in UltiSnipsSnippetDirectories. This directory is reserved for snipMate snippets. Use another directory for UltiSnips snippets.
~~~

please read the docs. you cannot have `'snippets'` in your UltiSnipsSnippetDirectories.

**Comment by primitivorm** [comment]
:echo g:UltiSnipsSnippetDirectories
['Ultisnips', 'snippets']

and I have in my _vimrc

set runtimepath+=~/vimfiles/
set runtimepath+=~/vimfiles/bundle/

personal snippets in 
~/vimfiles/snippets/*

ultisnipets in:
~/vimfiles/bundle/ultisnips/*

Is case sensitive directory name?

**Comment by primitivorm** [comment]
Hi Sirver:

I was install Plugin 'honza/vim-snippets' and its works OK, thanks for your HELP!

**Comment by SirVer** [comment]
This is wrong:
~~~
:echo g:UltiSnipsSnippetDirectories
['Ultisnips', 'snippets']
~~~
You must not add snippets in these directories. snipMate snippets will be picked up automatically unless disabled.

**Comment by primitivorm** [comment]
Thanks you very much Sirver.
I changed my global variable and works fine! 

let g:UltiSnipsSnippetDirectories=['Ultisnips']
