### ISSUE TITLE
_ box snippet fails when filetype is set to markdown

### ISSUE THREAD

**Issue by lpil** [SirVer/ultisnips#435]
Using vim-snippets snippets.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 144, in expand_or_jump
    rv = self._try_expand()
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 584, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 553, in _do_snippet
    self._cs.find_parent_for_new_to(start), start, end)
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 239, in launch
    snippet_instance.update_textobjects()
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 77, in update_textobjects
    if obj._update(done):
  File "/Users/louis/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 215, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 2, in <module>
  File "<string>", line 51, in make_box
  File "<string>", line 47, in _get_comment_format
IndexError: list index out of range
```

Cheers,
Louis

**Comment by SirVer** [comment]
Fixed in https://github.com/honza/vim-snippets/commit/0deb4bd28b615bb42352772ba4ebb975d90c71c8. But I think the `&comments` string is not correct in the markdown filetype - at least the created box seems wrong to me.

**Comment by lpil** [comment]
Thank you.
