### ISSUE TITLE
SyntaxError: invalid syntax when using "class" snippet for php

### ISSUE THREAD

**Issue by arthurprogramming** [SirVer/ultisnips#449]
When using "class" snippet for php

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 130, in expand
    if not self._try_expand():
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 584, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 558, in _do_snippet
    None, start, end)
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 239, in launch
    snippet_instance.update_textobjects()
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 77, in update_textobjects
    if obj._update(done):
  File "/home/arthur/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 215, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 5
    ›   snip.rv = m.group().replace('/', '\\')
    ^
SyntaxError: invalid syntax

**Comment by SirVer** [comment]
I do not know which version you track. But this is not what is at head at this repository - there is on syntax error at this point in the file. 

Try wiping your checkout and installing UltiSnips fresh - something in your version is fishy.

**Comment by arthurprogramming** [comment]
I'll try that
