### ISSUE TITLE
Ultisnips crashes on deleting expanded snippet

### ISSUE THREAD

**Issue by stuartmemo** [SirVer/ultisnips#460]
I've noticed an issue, which causes Ultisnips to crash when deleting an expanded snippet. Steps to reproduce...

1. Expand a snippet in an html document
2. Fill in the first placeholder, then tab to the 2nd one.
3. Go back into visual mode
4. Select all text, then delete
5. Repeat steps 1-4
6. App crashes.

Excuse the speed of the attached gif!

![ultisnips-bug](https://cloud.githubusercontent.com/assets/59205/6572221/6773e976-c708-11e4-8d85-0d59e468347c.gif)

Error output:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 330, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 77, in update_textobjects
    if obj._update(done):
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 128, in overwrite
    if self.current_text == gtext:
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
    return _vim.buf[self._start.line][self._start.col:self._end.col]
  File "/Users/browns79/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 23, in __getitem__
    rv = vim.current.buffer[idx]
IndexError: line number out of range
```

**Comment by SirVer** [comment]
Thanks for reporting. I can reproduce this - it only triggers if there is no text around your snippet (lines before, after).

**Comment by SirVer** [comment]
Can no longer repro in 324a4f8ffc491b05346c284fcbbb6f77318d6b82. Closing.
