### ISSUE TITLE
SnippetSyntaxError: Invalid line

### ISSUE THREAD

**Issue by acgtyrant** [SirVer/ultisnips#470]
Following is the full stack trace:
	Traceback (most recent call last):
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
	    return func(self, *args, **kwds)
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 130, in expand
	    if not self._try_expand():
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 574, in _try_expand
	    snippets = self._snips(before, False)
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 489, in _snips
	    source.ensure(filetypes)
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
	    self._load_snippets_for(ft)
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 73, in _load_snippets_for
	    self._parse_snippets(ft, fn)
	  File "/home/acgtyrant/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 89, in _parse_snippets
	    raise SnippetSyntaxError(filename, line_index, msg)
	SnippetSyntaxError: Invalid line '//==============================================================================' in dotfiles/Vim/.vim/snippets/c.snippets:7

**Comment by acgtyrant** [comment]
Here is my `c.snippets`: http://codepad.org/4tjKNpey

It works very good until I update SirVer/ultisnips via Vundle.

**Comment by SirVer** [comment]
Rename your snippets folder to UltiSnips. All files in snippets are now parsed as snipmate files - not UltiSnips.

**Comment by acgtyrant** [comment]
@SirVer Thank you!
