### ISSUE TITLE
Error loading 

### ISSUE THREAD

**Issue by demis001** [SirVer/ultisnips#478]
Installed using `git submodule add [path]  bundle/[blugin] ` ... with pathogen

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 130, in expand
    if not self._try_expand():
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 574, in _try_expand
    snippets = self._snips(before, False)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 489, in _snips
    source.ensure(filetypes)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
    self._load_snippets_for(ft)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 73, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "~/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 89, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '    import pdb; pdb.set_trace()' in snippets/python.snippets:2

**Comment by demis001** [comment]
solved, conflict with old snippets
