### ISSUE TITLE
i just install ultisnips as "Quick Start" said, when try  a snippet include "Python Interpolation", console thows errors as follow showing

### ISSUE THREAD

**Issue by king4throne** [SirVer/ultisnips#492]
my configure :

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsSnippetDirectories=['UltiSnips']
let g:UltiSnipsSnippetsDir = '~/.vim/UltiSnips'
" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger='\<tab\>'
let g:UltiSnipsJumpForwardTrigger='\<tab\>'
let g:UltiSnipsJumpBackwardTrigger='\<s-tab\>'
" show the list of snips
let g:UltiSnipsListSnippets='\<leader\>e'
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit='vertical'

----------------console   error------------------
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
Traceback (most recent call last):
请按 ENTER 或其它命令继续
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
  File "<string>", line 1, in <module>
请按 ENTER 或其它命令继续
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
  File "/home/fedorass/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 68, in wrapper
请按 ENTER 或其它命令继续
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
请按 ENTER 或其它命令继续
    _vim.new_scratch_buffer(msg)
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
  File "/home/fedorass/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in new_scratch_buffer
请按 ENTER 或其它命令继续
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
    vim.command('botright new')
请按 ENTER 或其它命令继续
处理 function UltiSnips#ExpandSnippetOrJump 时发生错误:
line  2:
vim.error: Vim(loadview):E32: 没有文件名

**Comment by king4throne** [comment]
in  Engilish
---------------------
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
Traceback (most recent call last):
ENTER for continue
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
  File "<string>", line 1, in <module>
ENTER for continue
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 68, in wrapper
ENTER for continue
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
ENTER for continue
    _vim.new_scratch_buffer(msg)
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in new_scratch_buffer
ENTER for continue
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
    vim.command('botright new')
ENTER for continue
processing function UltiSnips#ExpandSnippetOrJump triggers error:
line  2:
vim.error: Vim(loadview):E32: none file name

**Comment by SirVer** [comment]
Please delete all the lines but these for your UltiSnips configuration:

~~~
" Trigger configuration. Do not use if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsEditSplit='vertical'
~~~

And try again.

**Comment by king4throne** [comment]
i delete all (vundle manage)Plugins configs  in .vimrc just left:
```
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
```
and  ultisnips setting
```
" Trigger configuration. Do not use if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsEditSplit='vertical'
```
console thows errors as follow showing:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 53, in wrapper
    return func(self, *args, **kwds)
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 129, in expand_or_jump
    rv = self._try_expand()
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 520, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 495, in _do_snippet
    None, start, end)
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 222, in launch
    snippet_instance.update_textobjects()
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 67, in update_textobjects
    if obj._update(done):
  File "/home/fedoravim/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 199, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 12
    def __init__(self, arg)
                          ^
SyntaxError: invalid syntax
```

**Comment by king4throne** [comment]
i found that it is vim-snippets's problem. i update vim-snippets plugin, it works now.
thanks!
