### ISSUE TITLE
recent commits stopped ultisnips from recognizing valid snippets

### ISSUE THREAD

**Issue by xiaket** [SirVer/ultisnips#511]
I included ultisnips as a plugin and upstream in my etc/dotfiles repo, I'll do a submodule update from time to time. I recently updated it from 00848d7d64e7b736adbdb4bf4c05576ea42fb806 to 3806a6987405cd0459426949a8b115ff93bb7dcd, and my previously valid snippet is no longer correctly recognized:

```
snippet exit
import sys
sys.exit()
endsnippet

snippet datetime
from datetime import datetime
endsnippet

snippet ifmain
if __name__ == '__main__':
	main()
endsnippet
```

When in an empty python file,  after I wrote an ifmain and press Ctrl-J, UltiSnips would complain:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 146, in expand_or_jump
    rv = self._try_expand()
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 577, in _try_expand
    snippets = self._snips(before, False)
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 492, in _snips
    source.ensure(filetypes)
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
    self._load_snippets_for(ft)
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 74, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/xiaket/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line 'import sys' in .xiaket/share/repos/github/etc/vim/snippets/python.snippets:2
```

UltiSnip related vimrc excerpts:

```
inoremap <c-j> <c-r>=g:jInYCM()<cr>
au BufEnter,BufRead * exec "inoremap <silent> " . g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:kInYCM()<cr>"

" UltiSnip key mappings.
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" UltiSnip settings.
let g:UltiSnipsSnippetDirectories=["/Users/xiaket/.vim/snippets"]
let g:UltiSnipsDoHash=0

```

**Comment by SirVer** [comment]
This broke  much earlier than the commit you provided. The reason is that UltiSnips now also reads vim-snippets snippets. All snippets that are in a directory called snippets will be read as vim-snippet snippets. And you have snippets that aren't.

Simple fix:
`mv .xiaket/share/repos/github/etc/vim/snippets/ .xiaket/share/repos/github/etc/vim/UltiSnips`

**Comment by SirVer** [comment]
Oh, then also remove/modify the `let g:UltiSnipsSnippetDirectories=` line of course.
