### ISSUE TITLE
UltiSnips not parsing SnipMate snippets correctly when editing .snippets files

### ISSUE THREAD

**Issue by EdRice4** [SirVer/ultisnips#513]
This is my first ever issue submit so I apologize in advance if I did not provide enough information or I have formatted incorrectly. :)

# Error Description:

I am unsure whether or not this is an UltiSnips or vim-snippets bug but the behavior seems to suggest the former. I noticed this peculiar behavior when attempting to edit the python.snippets file (from the [vim-snippets](https://github.com/honza/vim-snippets) plugin) in my UltiSnips directory. Each time I attempt to expand the "snip" snip, I receive the following error:

`SnippetSyntaxError: Missing 'endsnippet' for 'lib' in snippets/dart.snippets:82`

The error itself seems to indicate that this .snippets file has not been recognized as a SnipMate snippet file and was therefore not parsed as such. Curious, I removed the offending fie and noticed an analogous pattern for each SnipMate snippet:

`SnippetSyntaxError: Missing 'endsnippet' for 'FIRST_SNIP' in snippets/SNIP_FILE.snippets:LINE#`

To that end, I removed the "snippets" directory entirely and this resolved the issue. However, this is not a tenable long-term solution as I would like to utilize some of the snips as defined by SnipMate in other projects. Yet, this error is only raised when editing .snippets files. That is to say, I am able to use snippets as defined by both UltiSnips and SnipMate while editing .py and other file types.

# Pertinent information:

## Full error code:

```python
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.
 
Following is the full stack trace:
Traceback (most recent call last):
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 146, in expand_or_jump
    rv = self._try_expand()
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 577, in _try_expand
    snippets = self._snips(before, False)
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 492, in _snips
    source.ensure(filetypes)
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
    self._load_snippets_for(ft)
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 74, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/edwin/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Missing 'endsnippet' for 'lib' in snippets/dart.snippets:82
```
### Of note:

The output of :set ft is: filetype=snippets
:UltiSnipsEdit produces a list of (and only of) .snippets file in "snippets" direcotory

## Directory setup:
- ~/.vim/
  - after/plugin/UltiSnips_after.vim (symlink) (a la [this bug](https://bugs.launchpad.net/ultisnips/+bug/1067416))
  - ftdetect/
    - snippets.vim (symlink)
    - UltiSnips.vim (symlink)
  - UltiSnips/
    - *.snippets
    - snippets/*.snippets

## .vimrc
```vim
" Remove cumbersome compatability with vi
set nocompatible

" Utilize vundle to readily manage runtimepaths
filetype off
set rtp+=~/.vim/bundle/vundle/
source ~/.vim/plugins.vim
filetype plugin indent on

set nowrap " don't wrap lines
set tabstop=4 " tab is four spaces
set softtabstop=4 " <BS> behaves as if tab removed
set expandtab " expand tabs (utilize spaces)
set shiftwidth=4 " spaces to utilize for autoindenting
set shiftround
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set showmatch
set ignorecase
set smartcase
set scrolloff=4
set gdefault " global (in line) as default
set smarttab
set hlsearch " highlight search terms
set incsearch
set pastetoggle=<F3> " toggle past mode
set shortmess+=I " hide launch screen
set clipboard=unnamedplus " normal os clipbaord interaction
set autoread " automatically reload files modified outside of vim
set ruler

" Security issue
set modelines=0

" Aesthetics
colorscheme gruvbox
set background=dark

" Remap leader to spacebar
let mapleader="\<Space>"

" toggle relative line numbers
nnoremap <silent> <leader>N :setlocal relativenumber!<cr>

" Fix regex
nnoremap / /\v
vnoremap / /\v

" Speed up scrolling of viewport
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Folding rules {{{
set foldenable                  " enable folding
set foldcolumn=2                " add a fold column
set foldmethod=marker           " detect fold levels based on indent
set foldlevelstart=99           " start out with everything unfolded
set foldopen=block,hor,insert,jump,mark,percent,quickfix,search,tag,undo
                                " which commands trigger auto-unfold

function! MyFoldText()
    let line = getline(v:foldstart)

    let nucolwidth = &fdc + &number * &numberwidth
    let windowwidth = winwidth(0) - nucolwidth - 3
    let foldedlinecount = v:foldend - v:foldstart

    " expand tabs into spaces
    let onetab = strpart('          ', 0, &tabstop)
    let line = substitute(line, '\t', onetab, 'g')

    let line = strpart(line, 0, windowwidth - 2 -len(foldedlinecount))
    let fillcharcount = windowwidth - len(line) - len(foldedlinecount) - 4
    return line . ' …' . repeat(" ",fillcharcount) . foldedlinecount . ' '
endfunction
set foldtext=MyFoldText()

" Mappings to easily toggle fold levels
nnoremap <silent> z0 :set foldlevel=0<cr>
nnoremap <silent> z1 :set foldlevel=1<cr>
nnoremap <silent> z2 :set foldlevel=2<cr>
nnoremap <silent> z3 :set foldlevel=3<cr>
nnoremap <silent> z4 :set foldlevel=4<cr>
nnoremap <silent> z5 :set foldlevel=5<cr>
nnoremap <silent> z6 :set foldlevel=6<cr>
nnoremap <silent> z7 :set foldlevel=7<cr>
nnoremap <silent> z8 :set foldlevel=8<cr>
nnoremap <silent> z9 :set foldlevel=9<cr>
" }}}

" Editor layout {{{
set termencoding=utf-8
set encoding=utf-8
set lazyredraw
set guifont=Source\ Code\ Pro\ Regular
let g:Powerline_symbols='fancy'
set laststatus=2
" }}}

" Vim behavior {{{
set hidden
set switchbuf=useopen
set history=1000
set undolevels=1000
if v:version >= 730
	set undofile
	set undodir=~/.vim/.undo,~/tmp,/tmp
endif
set nobackup
set noswapfile

set directory=~/.vim/.tmp,~/tmp,/tmp
set viminfo='20,\"80
set wildmenu
set wildmode=list:full
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set visualbell
set noerrorbells
set showcmd
set nomodeline
set ttyfast
set cursorline
" }}}

" Toggle the quickfix window {{{
" From Steve Losh, http://learnvimscriptthehardway.stevelosh.com/chapters/38.html
nnoremap <C-q> :call <SID>QuickfixToggle()<cr>

let g:quickfix_is_open = 0

function! s:QuickfixToggle()
    if g:quickfix_is_open
        cclose
        let g:quickfix_is_open = 0
        execute g:quickfix_return_to_window . "wincmd w"
    else
        let g:quickfix_return_to_window = winnr()
        copen
        let g:quickfix_is_open = 1
    endif
endfunction
" }}}

" Toggle the foldcolumn {{{
nnoremap <leader>f :call FoldColumnToggle()<cr>

let g:last_fold_column_width = 4  " Pick a sane default for the foldcolumn

function! FoldColumnToggle()
    if &foldcolumn
        let g:last_fold_column_width = &foldcolumn
        setlocal foldcolumn=0
    else
        let &l:foldcolumn = g:last_fold_column_width
    endif
endfunction
" }}}

" Highlighting {{{
if &t_Co > 2 || has("gui_running")
   syntax on                    " switch syntax highlighting on, when the terminal has colors
endif
" }}}

" make p in Visual mode replace the selected text with the yank register
vnoremap p <Esc>:let current_reg = @"<CR>gvdi<C-R>=current_reg<CR><Esc>

" Quick yanking to the end of the line
nnoremap Y y$

" Clears the search register
nnoremap <silent> <leader>/ :nohlsearch<CR>

" Easy window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
nnoremap <leader>w <C-w>v<C-w>l

" Mapping for NERDTree
map <F2> :NERDTreeToggle<CR>

" UltiSnips {{{
" Search directories
let g:UltiSnipsSnippetDirectories = [$HOME.'/.vim/UltiSnips/']

" Make US compatible with YCM
let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabContextDefaultCompletionType = '<C-n>' " being at top of completion window

" Better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsListSnippets = '<C-S-tab>'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<S-tab>'
inoremap TT <tab>

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit = 'vertical'
" }}}

" Rainbow {{{
let g:rainbow_conf = {
\   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
\   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
\   'operators': '_,_',
\   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\   'separately': {
\       '*': {},
\       'tex': {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
\       },
\       'lisp': {
\           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\       },
\       'vim': {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
\       },
\       'html': {
\           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
\       },
\       'css': 0,
\   }
\}

" Mapping
nnoremap <silent> <leader>R :RainbowToggle<cr>
" }}}

" Pulse {{{
let g:vim_search_pulse_mode = 'cursor_line'
" }}}

"Confiuration for YCM
let g:ycm_autoclose_preview_window_after_completion = 1  " Automatically close window after input

" Configuration for syntastic
let g:syntastic_python_flake8_args = '--ignore=E126,E123' " Ignore overindentation for hanging indent
```

## plugins.vim

```vim
" set the runtime path to include Vundle and initialize
" set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" call vundle#rc()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/.vim/plugins')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
Plugin 'gmarik/vundle'
Bundle 'Valloric/YouCompleteMe'
Bundle 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'flazz/vim-colorschemes'
Plugin 'scrooloose/syntastic'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-unimpaired'
Plugin 'luochen1990/rainbow'
Plugin 'inside/vim-search-pulse'

" All of your Plugins must be added before the following line
call vundle#end()
```

**Comment by SirVer** [comment]
Please try with head - it seems the version you are using does not support parsing snipMate snippets yet. Or at least it is not trying to parse the snippets you indicated as snipMate.

**Comment by EdRice4** [comment]
By "try with head" do you mean git pull the repo? Sorry for the ignorance
and thank you for the quick reply!

**Comment by SirVer** [comment]
yes - I mean using the current state of this repo.
