### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by Alok** [SirVer/ultisnips#561]
I got a message that says:

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
```
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 132, in expand
    if not self._try_expand():
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 616, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 586, in _do_snippet
    None, start, end)
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 280, in launch
    snippet_instance.update_textobjects()
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 78, in update_textobjects
    if obj._update(done):
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/Users/alokbeniwal/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 99, in eval
    rv = vim.eval(as_vimencoding(text))
error: Vim:E117: Unknown function: vim_snippets#Filename
```

**Comment by SirVer** [comment]
A really long time ago, UltiSnips came with a compatibility file for snipMate snippets that has been moved out of the repository into https://github.com/honza/vim-snippets/tree/master/autoload.

If you track honza/vim-snippets, this should work again. Please let me know if that didn't work.
