### ISSUE TITLE
UltiSnips possible bug on Ubuntu.

### ISSUE THREAD

**Issue by EderSantana** [SirVer/ultisnips#562]
I keep getting errors with python snippets, I'm using the default ones from honza's repo. They work fine on my mac, but keep crashing on a linux box. When I type Ctrl-b it just delete lines. If I type Ctrl-z they crash. Here is the error report. Can anybody help me?

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 59, in wrapper
    return func(self, *args, **kwds)
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand
    if not self._try_expand():
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 689, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 660, in _do_snippet
    self._jump()
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 473, in _jump
    _vim.select(ntab.start, ntab.end)
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 169, in select
    col = col2byte(start.line + 1, start.col)
  File "/home/eders/.vim/bundle/ultisnips/pythonx/UltiSnips/compatibility.py", line 82, in col2byte
    pre_chars = _vim_dec(vim.current.buffer[line - 1] + '  ')[:col]
IndexError: line number out of range
```

**Comment by SirVer** [comment]
Can you link the snippet you try and the exact keys you are pressing in a new buffer? Also what is your UltiSnips configuration?

**Comment by EderSantana** [comment]
I'm trying to use this snippet: https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L244-L264

I type `class<F2>` in insert mode. It works OK calling up the template. If I press `<c-b>` or `<c-z>` things crash. My `vimrc` looks like this:
``` vimL
let g:UltiSnipsExpandTrigger="<F2>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetsDir='~/.vim/UltiSnips'
```

**Comment by SirVer** [comment]
I cannot reproduce that at HEAD on linux in gvim. Could it be that you have some bad interplay with other plugins? Could you try to reduce your vimrc to a minimal repro case?

**Comment by SirVer** [comment]
Closing this due to inactivity.

**Comment by EderSantana** [comment]
sure, sorry!
