### ISSUE TITLE
Unable to expand rst.snippets

### ISSUE THREAD

**Issue by francozappa** [SirVer/ultisnips#568]
I tried to use `part` `sec` and `ssec` reStructuredText snippets but I got the following stack trace

Following is the full stack trace:
Traceback (most recent call last):
 File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 53, in wrapper
    return func(self, *args, **kwds)
 File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 129, in expand_or_jump
    rv = self._try_expand()
 File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 520, in _try_expand
    self._do_snippet(snippet, before)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 495, in _do_snippet
    None, start, end)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet/definition/_base.py", line 222, in launch
    snippet_instance.update_textobjects()
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 67, in update_textobjects
    if obj._update(done):
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/text_objects/_python_code.py", line 199, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 7, in <module>
ImportError: No module named vimsnippets

**Comment by SirVer** [comment]
where did you get these snippets from? the last line indicates, that [this directory](https://github.com/honza/vim-snippets/tree/master/pythonx) is not in your `&rtp` variable.

**Comment by francozappa** [comment]
I got them installing [this package from Arch Linux community repo](https://www.archlinux.org/packages/community/any/vim-ultisnips/). 

I'm running Manjaro Linux 64-bit distro.

**Comment by SirVer** [comment]
then they do not install everything. Seems like a packaging bug to me.
