### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kovetskiy** [SirVer/ultisnips#571]
Hi, I got a hangup while using vim with ultisnips today.

I connected to vim using 
```strace -p `pidof vim` -f```
and got:
```
[pid 12868] brk(0x46d7a000)             = 0x46d7a000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafde78000
[pid 12868] brk(0x46d9c000)             = 0x46d9c000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafde38000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafddf8000
[pid 12868] brk(0x46dc0000)             = 0x46dc0000
[pid 12868] brk(0x46e04000)             = 0x46e04000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdcf8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdcb8000
[pid 12868] brk(0x46e25000)             = 0x46e25000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdc78000
[pid 12868] brk(0x46e47000)             = 0x46e47000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdc38000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdbf8000
[pid 12868] brk(0x46e68000)             = 0x46e68000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdbb8000
[pid 12868] brk(0x46e8c000)             = 0x46e8c000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdb78000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdb38000
[pid 12868] brk(0x46eaf000)             = 0x46eaf000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdaf8000
[pid 12868] brk(0x46ed3000)             = 0x46ed3000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdab8000
[pid 12868] munmap(0x7faafdab8000, 262144) = 0
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafdab8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafda78000
[pid 12868] brk(0x46ef5000)             = 0x46ef5000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafda38000
[pid 12868] brk(0x46f17000)             = 0x46f17000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd9f8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd9b8000
[pid 12868] brk(0x46f3c000)             = 0x46f3c000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd978000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd938000
[pid 12868] brk(0x46f5e000)             = 0x46f5e000
[... too many mmap() and brk() ...]
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd8f8000
[pid 12868] brk(0x46f81000)             = 0x46f81000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd8b8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd878000
[pid 12868] brk(0x46fa5000)             = 0x46fa5000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd838000
[pid 12868] brk(0x46fc8000)             = 0x46fc8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd7f8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd7b8000
[pid 12868] brk(0x46fe9000)             = 0x46fe9000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd778000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd738000
[pid 12868] brk(0x4700d000)             = 0x4700d000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd6f8000
[pid 12868] brk(0x47031000)             = 0x47031000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd6b8000
[pid 12868] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faafd678000
[pid 12868] mmap(NULL, 3221229568, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
[pid 12868] brk(0x10703e000)            = 0x47031000
[pid 12868] mmap(NULL, 3221360640, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
[pid 12868] mmap(NULL, 3221229568, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
[pid 12868] brk(0x10703e000)            = 0x47031000
[pid 12868] mmap(NULL, 3221360640, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
[pid 12868] stat("/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", {st_mode=S_IFREG|0644, st_size=30725, ...}) = 0
[pid 12868] open("/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", O_RDONLY) = 6
[pid 12868] fstat(6, {st_mode=S_IFREG|0644, st_size=30725, ...}) = 0
[pid 12868] fstat(6, {st_mode=S_IFREG|0644, st_size=30725, ...}) = 0
[pid 12868] mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facb7084000
[pid 12868] read(6, "#!/usr/bin/env python\n# encoding"..., 31232) = 30725
[pid 12868] read(6, "", 31232)          = 0
[pid 12868] close(6)                    = 0
[pid 12868] munmap(0x7facb7084000, 32768) = 0
[pid 12868] stat("/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", {st_mode=S_IFREG|0644, st_size=30725, ...}) = 0
[pid 12868] stat("/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/_diff.py", {st_mode=S_IFREG|0644, st_size=9817, ...}) = 0
[pid 12868] open("/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/_diff.py", O_RDONLY) = 6
[pid 12868] fstat(6, {st_mode=S_IFREG|0644, st_size=9817, ...}) = 0
[pid 12868] fstat(6, {st_mode=S_IFREG|0644, st_size=9817, ...}) = 0
[pid 12868] mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facb7089000
[pid 12868] read(6, "#!/usr/bin/env python\n# encoding"..., 10240) = 9817
[pid 12868] read(6, "", 10240)          = 0
[pid 12868] close(6)                    = 0
[pid 12868] munmap(0x7facb7089000, 12288) = 0
[pid 12868] getcwd("/home/vxw/go/src/git.rn/devops/sould", 4096) = 37
[pid 12868] recvmsg(4, 0x7ffc1aac0eb0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] recvmsg(4, 0x7ffc1aac0eb0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] poll([{fd=4, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 12868] select(5, [0 4], NULL, [0], {0, 0}) = 1 (in [0], left {0, 0})
[pid 12868] read(0, "\7\7\7\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3", 4080) = 30
[pid 12868] munmap(0x7fac9c578000, 262144) = 0
[pid 12868] munmap(0x7fac9c538000, 262144) = 0
[pid 12868] munmap(0x7fac9c4b8000, 262144) = 0
[pid 12868] munmap(0x7fac9c5f9000, 262144) = 0
```
`top` measured vim resident memory usage as 9GiB, I sent 'ctrl-c' to terminal with vim and this "leaked" memory has been free.

in vim I got a python stack trace:
```
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
Traceback (most recent call last):                                                                                     
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "<string>", line 1, in <module>                                                                                 
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 70, in wrapper                     
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
    self._leaving_buffer()  # pylint:disable=protected-access                                                          
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 421, in _leaving_buffer            
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
    self._current_snippet_is_done()                                                                                    
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 442, in _current_snippet_is_done   
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
    self._teardown_inner_state()                                                                                       
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 387, in _teardown_inner_state      
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
    _vim.command('silent doautocmd User UltiSnipsExitLastSnippet')                                                     
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
  File "/home/vxw/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 115, in command                               
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
    return as_unicode(vim.command(as_vimencoding(cmd)))                                                                
Press ENTER or type command to continue                                                                                
Error detected while processing function UltiSnips#CursorMoved:                                                        
line    1:                                                                                                             
KeyboardInterrupt                                                                                                      
Press ENTER or type command to continue                                                                                
````

Also, after many  "munmap()" `strace` show some work with YouCompleteMe (I guess it's can be useful info)
```
[pid 12868] munmap(0x7fabb973a000, 262144) = 0
[pid 12868] munmap(0x7fabc84fa000, 262144) = 0
[pid 12868] munmap(0x7fabbd0ba000, 262144) = 0
[pid 12868] munmap(0x7fab9d239000, 262144) = 0
[pid 12868] munmap(0x7fac1063c000, 262144) = 0
[pid 12868] munmap(0x7fab18638000, 262144) = 0
[pid 12868] munmap(0x7fababa3a000, 262144) = 0
[pid 12868] munmap(0x7fabf99bb000, 262144) = 0
[pid 12868] munmap(0x7fabe353a000, 262144) = 0
[pid 12868] munmap(0x7fab97c39000, 262144) = 0
[pid 12868] munmap(0x7fab06e38000, 262144) = 0
[pid 12868] munmap(0x7fab0bb38000, 262144) = 0
[pid 12868] munmap(0x7fabb0a3a000, 262144) = 0
[pid 12868] munmap(0x7fabaf5ba000, 262144) = 0
[pid 12868] munmap(0x7fabcd13a000, 262144) = 0
[pid 12868] munmap(0x7fac1c37e000, 262144) = 0
[pid 12868] munmap(0x7fabd013a000, 262144) = 0
[pid 12868] munmap(0x7fabb41ba000, 262144) = 0
[pid 12868] munmap(0x7fab27f38000, 262144) = 0
[pid 12868] munmap(0x7fac0463c000, 262144) = 0
[pid 12868] munmap(0x7fabd8e3a000, 262144) = 0
[pid 12868] munmap(0x7fabfccfb000, 262144) = 0
[pid 12868] munmap(0x7fabead3b000, 262144) = 0
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/requests/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/waitress/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/frozendict/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/requests/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/requests-futures/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/ycmd/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/retries/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/third_party/pythonfutures/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/autoload/../third_party/ycmd/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/home/vxw/.vim/bundle/YouCompleteMe/autoload/../python/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python27.zip/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/plat-linux2/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/lib-tk/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/lib-old/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/lib-dynload/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("/usr/lib/python2.7/site-packages/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] open("_vim_path_/<string>", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 12868] recvmsg(4, 0x7ffc1aac1460, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] recvmsg(4, 0x7ffc1aac1460, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] poll([{fd=4, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 12868] select(5, [0 4], NULL, [0], {0, 0}) = 0 (Timeout)
[pid 12868] write(1, "\33[0m\33[38;5;238m\33[48;5;255m\r\r\n   "..., 888) = 888
[pid 12868] recvmsg(4, 0x7ffc1aac12b0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] recvmsg(4, 0x7ffc1aac12b0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 12868] poll([{fd=4, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 12868] select(5, [0 4], NULL, [0], {0, 150000}) = 0 (Timeout)
```

**Comment by SirVer** [comment]
UltiSnips is not prone to leaking memory - as a python tool it can only leak if there are cycles in the object  graph which we always try to avoid

However, due to https://github.com/SirVer/ultisnips/issues/155 UltiSnips can occasionally take a lot of memory - maybe even as much as you saw. I consider this bug therefore a duplicate - unlikely to be fixed in Vim.

**Comment by dqgthb** [comment]
I'm having exactly the same error. It happens if I leave the vim session open for a while without changing anything (such as taking a 10 minutes break and coming back), and when I come back from my break, it continuously spits the error above and I cannot insert a single character anymore. I should quit vim using :wq and come back and then everything becomes fine for a while, but same thing happens again and again. I feel it gets worse if I use Ultisnips together with other plugins using python such as deoplete or youcompleteme. It is very difficult to debug (for me) as it occurs with unknown time interval. This has been driving me crazy for a few months and, after tons of trials, I finally made the decision to change to emacs instead of using vim. It took me about 2 weeks and I'm not yet fully migrated, but it's funny that I now somehow appreciate this error as this introduced me a whole new world of emacs. But anyhow, hopefully this error can be resolved in the near future.
