### ISSUE TITLE
why ultisnip doesn't run well again after I PluginUpdate my vim through vundle

### ISSUE THREAD

**Issue by mirzalazuardi** [SirVer/ultisnips#590]
I really love this plugin. but I have a problem.
why ultisnip doesn't run well again after I PluginUpdate my vim through vundle?
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 59, in wrapper
    return func(self, *args, **kwds)
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 194, in list_snippets
    snippets = self._snips(before, True)
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 558, in _snips
    source.ensure(filetypes)
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
    self._load_snippets_for(ft)
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 74, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/MyMac/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '  def set_${1:model_class_name}' in ~/.vim/bundle/vim-snippets/snippets/rails.snippets:109
```

**Comment by mirzalazuardi** [comment]
[solved] I remove plugin list on my vimrc PluginClean and PluginInstall (reinstall all). and it works
