### ISSUE TITLE
An error when I insert a snippet and then undo it

### ISSUE THREAD

**Issue by yanqd0** [SirVer/ultisnips#629]
I write a snippet in `java.snippets`:

```snippets
snippet iclass "A inner class" bm
class ${1:ClassName} {

	protected ${1/(\w+).*/$1/}() {
		${0:// TODO: Default constructor.}
	}

}
```

When I insert `iclass<Tab>` and then undo it once again, there will be an error.
The repetition probability is nearly **50%** in my computer.

> Following is the full stack trace:
> Traceback (most recent call last):
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
>     return func(self, *args, **kwds)
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 368, in _cursor_moved
>     self._csnippets[0].update_textobjects()
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 79, in update_textobjects
>     if obj._update(done):
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_mirror.py", line 26, in _update
>     self.overwrite(self._get_text())
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 128, in overwrite
>     if self.current_text == gtext:
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
>     return _vim.buf[self._start.line][self._start.col:self._end.col]
>   File "/Users/yanqd0/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 25, in __getitem__
>     rv = vim.current.buffer[idx]
> IndexError: line number out of range

**Comment by seletskiy** [comment]
@yanqd0: I cannot reproduce, can you give more specific test setup?

**Comment by yanqd0** [comment]
Sorry for late.

![ultisnips_bug](https://cloud.githubusercontent.com/assets/8525143/12470194/3e20b044-c02d-11e5-80c5-5fac8911da89.gif)

As shown by the GIF above, when I undo `iclass` for the **second** time, something weird happened. When the **forth** time, a crash happened.

**Comment by seletskiy** [comment]
@yanqd0: Can't reproduce. Can you try to create simplest test case possible?
