### ISSUE TITLE
Ultisnips can't find certain snippets.

### ISSUE THREAD

**Issue by jottr** [SirVer/ultisnips#630]
Relevant bits of my `.vimrc`:

```
$ cat .vimrc
...
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
...
" UltiSnips --------------------------------------------------{{{3


let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/bundle/vim-snippets/snippets', 'UltiSnips']

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
...
```

In vim:

```
:echo UltisSnipsSnippetsDirectories
['/Users/jottr/.vim/bundle/vim-snippets/snippets', 'UltiSnips']

```

```
:set ft=html

html<Tab>
```
:boom: 

```
Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 165, in expand
    if not self._try_expand():
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 717, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 591, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/jottr/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Missing 'endsnippet' for 'nbs' in ~/.vim/bundle/vim-snippets/snippets/html.snippets:879
```

**Comment by seletskiy** [comment]
@jottr: Please, read error report carefully. It says you have incorrect snippet syntax:

```
SnippetSyntaxError: Missing 'endsnippet' for 'nbs' in ~/.vim/bundle/vim-snippets/snippets/html.snippets:879
```

**Comment by jottr** [comment]
This is the snippet from the official snippets repo: https://github.com/honza/vim-snippets/blob/master/snippets/html.snippets#L879
As you can see, none of those snippets have an `endsnippet` section.

Strangely the crash did not happen again though.

**Comment by seletskiy** [comment]
@jottr: Because it's legacy snipmate snippets. Adding snipmate directory with snipmate snippets to the `g:UltiSnipsSnippetsDir` is not correct. Please, refer to `:h g:UltiSnipsEnableSnipMate` for more info.
