### ISSUE TITLE
Invalid line '  import ${0:module}'

### ISSUE THREAD

**Issue by dduuch** [SirVer/ultisnips#642]
Hello,
I try to write while <wh> and I get this error:

```
Following is the full stack trace:                                              
Traceback (most recent call last):                                              
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)                                            
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 165, in expand
    if not self._try_expand():                                                  
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 717, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)                     
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 591, in _snips
    source.ensure(filetypes, cached=autotrigger_only)                           
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)                                                 
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)                                                
  File "/root/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)                         
SnippetSyntaxError: Invalid line '    import ${0:module}' in ~/.vim/snippets/python.snippets:8
```

**Comment by seletskiy** [comment]
@dduuch: I guess you have incorrect syntax in your snippet file. Please paste at least first 8 lines of the ~/.vim/snippets/python.snippets.

**Comment by dduuch** [comment]
I resolved it. 
The problem was, that I have create new directory ~/.vim/snippets  and I download python.snippets from vim-snippets and after this I have installed vim-snippets and ultisnips with Vundle.

When I remove dir ~/.vim/snippets all is fine ;)
