### ISSUE TITLE
Traceback when using default snippets file in honza/vim-snippets

### ISSUE THREAD

**Issue by siddharthist** [SirVer/ultisnips#653]
## Current issue: 
UltiSnips fails when using [the sample latex snippet file](https://github.com/honza/vim-snippets/blob/master/UltiSnips/tex.snippets#L5-L9). For details, read on.  

Solution: I had my snippets file under ~/.vim/snippets, instead of ~/.vim/UltiSnips, as stated in the docs. 

## Original problem
The snippet (for LaTeX's qtree package, if it matters):
```
snippet tree1
	\begin{figure}[H]
		\begin{center}
			\hfill
			\Tree[.${1:root}
					[.${2:lvl1}

						[.${3:lvl2} [.$\vdots$ ]]]
                    ]
			\hfill
		\end{center}
		\caption{${4:caption}}
		\label{fig:$4}
	\end{figure}
```
The traceback:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 820, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 717, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 591, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '                    ]' in ~/.vim/snippets/tex.snippets:184
```
line 184 is indeed the one with just the "]" on it.

**Comment by siddharthist** [comment]
Perhaps connectedly, when I put that bracket immediately after the ones that preceed it, I get this traceback instead:
```
Traceback (most recent call last):
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 820, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 717, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 591, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '                    [.$2' in ~/.vim/snippets/tex.snippets:200
```
Which is here:
```
snippet tree2
        \begin{figure}[H]
                \begin{center}
                        \hfill
                        \Tree[.${1:root}
                                        [.${2:lvl1}

                                                [.${3:lvl2} [.$\vdots$ ]]

                                                [.$3 [.$\vdots$ ]]]
                    [.$2

                                                [.${3:lvl2} [.$\vdots$ ]]

                                                [.$3 [.$\vdots$ ]]] ]
                        \hfill
                \end{center}
                \caption{${4:caption}}
                \label{fig:$4}
        \end{figure}
```

**Comment by siddharthist** [comment]
Both templates work fine if I just put all of the tree on a single line. I'm guessing that ultisnips doesn't like mismatched brackets in a single line?

**Comment by seletskiy** [comment]
@siddharthist: It looks like you're trying to use snipMate-syntax snippets, that are stored in the directory where UltiSnips expects to see only UltiSnips-syntax snippets.

Also, I recommend to switch on UltiSnips-syntax, it's more powerful.

**Comment by siddharthist** [comment]
@seletskiy Thanks for the quick response! Can you point me to the documentation for that syntax?

**Comment by seletskiy** [comment]
@siddharthist: See `:h UltiSnips-syntax`.

**Comment by siddharthist** [comment]
@seletskiy Thanks! Go ahead and close this issue if you dont support snipmate syntax. Sorry about my mixup!

**Comment by seletskiy** [comment]
@siddharthist: I'll wait until you provide feedback about not having the issue with US-syntax. I do not know intention about snipMate from original owner (@SirVer), but I do not want to support that outdated syntax.

**Comment by siddharthist** [comment]
@seletskiy Quick question: I'm having trouble figuring out the escaping of curly braces in the US syntax. If I'm writing a latex snippet like the following:
```
snippet begin
\begin{${1:env}}
    ${0}
\end{$1}
```
What needs to be escaped, and how? Thanks again for your support.

**Comment by siddharthist** [comment]
Never mind, just found https://github.com/honza/vim-snippets/blob/master/UltiSnips/tex.snippets

**Comment by SirVer** [comment]
The idea for snipMate was to get access to most snippets in https://github.com/honza/vim-snippets and make transition from snipMate to UltiSnips easier for people who didn't want to commit. It was a good PR decision and brought UltiSnips a ton of new users. Many users use UltiSnips on their dev machine and vim-snippets on underpowered remote machines. And snipMate is still more widely distributed than UltiSnips.

@seletskiy Your call of course, but I guess you'll annoy quite some users if you remove support for snipMate.

**Comment by siddharthist** [comment]
Actually @seletskiy I'm having trouble running the example https://github.com/honza/vim-snippets/blob/master/UltiSnips/tex.snippets#L5-L9. Could you take a look? 
```
Traceback (most recent call last):
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 820, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 717, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 591, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/siddharthist/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '\\begin{${1:something}}' in ~/.vim/snippets/tex.snippets:8
```

**Comment by SirVer** [comment]
@siddharthist That is because you tell UltiSnips that this is an snipMate snippet file (which it is not). Files in a 'snippet' directory are always assumed to be a snipMate file as stated in the docs.

Copy the tex file into `~/.vim/UltiSnips/tex.snippets` instead (or wherever your UltiSnips snippet file are).

**Comment by siddharthist** [comment]
Sorry to distract both of you! While the original issue with the SnipMate compatibility might've been valid, you definitely went above and beyond in terms of support :) I've got it all working and will be able to take notes in class tomorrow!
