### ISSUE TITLE
Regex {1/*/=/} let ultisnippets crash

### ISSUE THREAD

**Issue by shibumi** [SirVer/ultisnips#655]
Not sure if this is important and the behaviour is maybe also strange (because nobody is doing this) but I can crash ultisnippets with the following regex:

```
${1}
${1/*/=/}
```

seems like the problem is the *-operator..

Here is the stacktrace:
```
Following is the full stack trace:
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 163, in expand
    if not self._try_expand():
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 725, in _try_expand
    self._do_snippet(snippet, before)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 680, in _do_snippet
    None, start, end)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet/definition/_base.py", line 419, in launch
    self.instantiate(snippet_instance, initial_text, indent)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet/definition/ultisnips.py", line 15, in instantiateFollowing is the full stack trace:
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 163, in expand
    if not self._try_expand():
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet_manager.py", line 725, in _try_expand
    self._do_snippet(snippet, before)

    return parse_and_instantiate(snippet_instance, initial_text, indent)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet/parsing/ultisnips.py", line 49, in parse_and_instantiate
    _create_transformations(all_tokens, seen_ts)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/snippet/parsing/ultisnips.py", line 35, in _create_transformations
    Transformation(parent, seen_ts[token.number], token)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/text_objects/_transformation.py", line 158, in __init__
    TextObjectTransformation.__init__(self, token)
  File "/usr/share/vim/vimfiles/pythonx/UltiSnips/text_objects/_transformation.py", line 130, in __init__
    self._find = re.compile(token.search, flags | re.DOTALL)
  File "/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

**Comment by seletskiy** [comment]
@shibumi: Read the last line from stacktrace: `sre_constants.error: nothing to repeat at position 0`. It's invalid regexp.
