### ISSUE TITLE
python error: TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by Xunius** [SirVer/ultisnips#657]
I'm setting up vim on a manjaro laptop and got into this error: 

```
TypeError: can't multiply sequence by non-int of type 'float'
```

when trying to use a snippet that I've been using on multiple machines.

I guess it is related to the default python 3 manjaro uses. I tried to build a link to python2 by
`ln -sf python2 python` to use python2 but the error still occurs.

Here is the complete error message:
```
An error occured. This is either a bug in UltiSnips     or a bug in a
  2 snippet definition. If you think this is a bug, plea    se report it to
  3 https://github.com/SirVer/ultisnips/issues/new.
  4 
  5 Following is the full stack trace:
  6 Traceback (most recent call last):
  7   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 61, in     wrapper
  8     return func(self, *args, **kwds)
  9   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 165, in     expand
 10     if not self._try_expand():
An error occured. This is either a bug in UltiSnips     or a bug in a
  2 snippet definition. If you think this is a bug, plea    se report it to
  3 https://github.com/SirVer/ultisnips/issues/new.
  4 
  5 Following is the full stack trace:
  6 Traceback (most recent call last):
  7   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 61, in     wrapper
  8     return func(self, *args, **kwds)
  9   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 165, in     expand
 10     if not self._try_expand():
An error occured. This is either a bug in UltiSnips     or a bug in a
  2 snippet definition. If you think this is a bug, plea    se report it to
  3 https://github.com/SirVer/ultisnips/issues/new.
  4 
  5 Following is the full stack trace:
  6 Traceback (most recent call last):
  7   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 61, in     wrapper
  8     return func(self, *args, **kwds)
  9   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 165, in     expand
 10     if not self._try_expand():
  File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 747, in     _try_expand
 12     self._do_snippet(snippet, before)
 13   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet_manager.py", line 702, in     _do_snippet
 14     None, start, end)
 15   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/snippet/definition/_base.py", lin    e 421, in launch
 16     snippet_instance.update_textobjects()
 17   File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/text_objects/_snippet_instance.py    ", line 79, in update_textobjects
 18     if obj._update(done):
  File "/home/guangzhi/.vim/vundle-plugins/ultisnips    /pythonx/UltiSnips/text_objects/_python_code.py", li    ne 271, in _update
 20     exec(code, self._locals)  # pylint:disable=exec-    used
 21   File "<string>", line 1, in <module>
 22   File "<string>", line 2, in fillUpLine
 23 TypeError: can't multiply sequence by non-int of typ    e 'float'
 24 
 25 Executed snippet code:
 26   1   snip.rv=fillUpLine(t[3])
```

**Comment by Xunius** [comment]
Ok problem solved. I need to make sure to cast the float to int in the fillUpLine function. Didn't have this issue before.
