### ISSUE TITLE
Undefined variable: g:SuperTabMappingBackward'

### ISSUE THREAD

**Issue by romanmt** [SirVer/ultisnips#667]
I get this error every time I press tab in a javascript file. I'm using NeoVim 0.1.2

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/matt/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "/Users/matt/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 167, in expand
    self._handle_failure(self.expand_trigger)
  File "/Users/matt/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 572, in _handle_failure
    _vim.eval('g:SuperTabMappingBackward'),
  File "/Users/matt/.vim/plugged/ultisnips/pythonx/UltiSnips/_vim.py", line 117, in eval
    rv = vim.eval(as_vimencoding(text))
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 124, in eval
    return self._session.request('vim_eval', string, async=async)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 230, in request
    return walk(self._in, self._session.request(name, *args, **kwargs),
  File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 90, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E121: Undefined variable: g:SuperTabMappingBackward'

**Comment by ScriptorNY** [comment]
Same problem here, but every time I type something. I also use neovim. Here is my [config file](https://gist.github.com/ScriptorNY/63c61ea14d085c947ab2).

Thank you very much in advance

**Comment by seletskiy** [comment]
@romanmt: Please, evaluate following commands at the vim command line after you will see error:

```
py print(vim.eval('exists("g:SuperTabMappingForward")'))
py print(vim.eval('exists("g:SuperTabMappingBackward")'))
```

**Comment by romanmt** [comment]
@seletskly, thanks for getting back to me. I removed SuperTab and the problem went away. I no longer need SuperTab so this is acceptable. Sorry for not closing the issue sooner.
