### ISSUE TITLE
Error when pressing F-key in insert mode

### ISSUE THREAD

**Issue by rcorre** [SirVer/ultisnips#691]
press `i<F4>` (or any F-key that is unbound in insert mode).
It does eventually insert '<F4>', but shows:

```
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/rcorre/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 61, in wrapper
Error detected while processing function UltiSnips#TrackChange:
line    1:
    return func(self, *args, **kwds)
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/rcorre/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 883, in _track_change
Error detected while processing function UltiSnips#TrackChange:
line    1:
    inserted_char = _vim.eval('v:char')
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/rcorre/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 117, in eval
Error detected while processing function UltiSnips#TrackChange:
line    1:
    rv = vim.eval(as_vimencoding(text))
Error detected while processing function UltiSnips#TrackChange:
line    1:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte
Error detected while processing function UltiSnips#TrackChange:
line    1:
Error detected while processing function UltiSnips#TrackChange:
line    1:
During handling of the above exception, another exception occurred:
Error detected while processing function UltiSnips#TrackChange:
line    1:
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/rcorre/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 94, in wrapper
Error detected while processing function UltiSnips#TrackChange:
line    1:
    _vim.new_scratch_buffer(msg)
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "/home/rcorre/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 145, in new_scratch_buffer
Error detected while processing function UltiSnips#TrackChange:
line    1:
    vim.command('botright new')
Error detected while processing function UltiSnips#TrackChange:
line    1:
vim.error: Vim(new):E523: Not allowed here: botright new

```

**Comment by seletskiy** [comment]
Thanks! I will fix it soon.

**Comment by yubo56** [comment]
Bump? Seeing this too

**Comment by pnloyd** [comment]
+1, this bug is really annoying.

**Comment by bennyyip** [comment]
+1, I encounter the same bug.

**Comment by mjansing** [comment]
Any updates on this issue?

**Comment by Firsta** [comment]
+1

**Comment by seletskiy** [comment]
@Firsta, @mjansing, @bennyyip, @pnloyd, @yubo56, @rcorre: try latest master, please.

**Comment by yubo56** [comment]
I see that it's fixed!!! Such a small but pleasant QoL issue, thanks much much

**Comment by SirVer** [comment]
Fixed in master.
