### ISSUE TITLE
SnippetSyntaxError: Invalid line

### ISSUE THREAD

**Issue by damionvega** [SirVer/ultisnips#703]
```
Traceback (most recent call last):
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 846, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 705, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 578, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/mbp/.nvim/plugs/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line "'use strict'" in .config/nvim/snippets/javascript.snippets:3
```

Here's the snippet the error comes across:
```
# Use strict
snippet u
'use strict'
${1}
endsnippet
```

My config:
```
  let g:UltiSnipsExpandTrigger = '<tab>'
  let g:UltiSnipsJumpForwardTrigger = '<tab>'
  let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
  let g:UltiSnipsSnippetDirectories = [$HOME.'/.config/nvim/snippets']
  nmap <leader>ue :UltiSnipsEdit<CR>
```

NVIM 0.1.5-dev
OSX 10.11.4 

Snippets file: https://github.com/damionvega/dotfiles/blob/master/.config/nvim/snippets/javascript.snippets

**Comment by damionvega** [comment]
Got it to work by updating the following:
`let g:UltiSnipsSnippetDirectories = [$HOME.'/.config/nvim/snippets']`
to
`let g:UltiSnipsSnippetDirectories = [$HOME.'/.config/nvim/ultisnips']`

But why?

**Comment by seletskiy** [comment]
@damionvega: `snippets` directory is reserved for snipMate-syntax snippets, that the reason why you see errorr.
