### ISSUE TITLE
Line number out of range in _vim.py

### ISSUE THREAD

**Issue by kovetskiy** [SirVer/ultisnips#715]
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 345, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 295, in _update
    ct = self.current_text
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
    return _vim.buf[self._start.line][self._start.col:self._end.col]
  File "/home/operator/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 25, in __getitem__
    rv = vim.current.buffer[idx]
IndexError: line number out of range
```

**Comment by SirVer** [comment]
No repro case, closing as not-reproducible.
