### ISSUE TITLE
expand snip "box" in all.snippet and get wrong "IndexError: string index out of range"

### ISSUE THREAD

**Issue by Alan110** [SirVer/ultisnips#717]
when expand  "box" or "bbox" , it will show that:
 
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
    rv = self._try_expand()
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 721, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 676, in _do_snippet
    None, start, end)
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/Users/alan/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 308, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 2, in <module>
  File "/Users/alan/.vim/bundle/vim-snippets/pythonx/vimsnippets.py", line 83, in make_box
    sline = b + m + bwidth_inner * m[0] + 2 * m[0]
IndexError: string index out of range

Executed snippet code:
  1
  2   box = make_box(len(t[1]))
  3   snip.rv = box[0]
  4   snip += box[1]
  5

____

other snippets work well .  i don't know what reason cause that.  so i'm here...

Python 2.7.10  
vim 7.4.884

**Comment by seletskiy** [comment]
@Alan110: Read stacktrace carefully, it's obviously error in your code (`vimsnippets.py`), not in UltiSnips.
