### ISSUE TITLE
Possible issues on Ubuntu 14.04

### ISSUE THREAD

**Issue by Chenlonw** [SirVer/ultisnips#728]
```
Following is the full stack trace:
Traceback (most recent call last):
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 705, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 578, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/chlwang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line 'endsnippet' in snippets/c.snippets:3
```

This error occurs when I use F2 to toggle Ultisnips in gvim on ubuntu14.04
my configuration is
```vim
let g:UltiSnipsExpandTrigger="<F2>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetsDir='~/.vim/snippets'
```
and c.snipets
```
snippet def "#define ..."
#define ${1}
endsnippet
```
can anybody help me to solve it?

**Comment by seletskiy** [comment]
@Chenlonw: `~/.vim/snippets` directory is reserved for the snipMate syntax snippets. Use directory named `UltiSnips` or simething like that.

**Comment by Chenlonw** [comment]
Thx a lot.  It works now.
