### ISSUE TITLE
undefined variable: 'v' when using vimshell.

### ISSUE THREAD

**Issue by dylnmc** [SirVer/ultisnips#758]
I haven't been able to get any interpolation working with _UltiSnips_. I have read the documentation, and watched tutorials, but it just doesn't seem to work. In my _python.snippets_, when I use this snippet

```
snippet le "last edit"
	# last edited: `!v echo strftime("%c")`
```

(I have also tried)

```
snippet le "last edit"
	# last edited: `!v strftime("%c")`
```

(and a lot of other things ... but the problem seems to be the '!v' or that the backticks aren't evaluating things right)

I get the following error. 

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/home/dylnmc/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
  File "/usr/lib/python3.5/site-packages/neovim/plugin/script_host.py", line 187, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E121: Undefined variable: v'

```

All of my snippets are stored in _~/.config/nvim/plugged/vim-snippets/UltiSnips/_ and I use `let g:UltiSnipsSnippetsDir="~/.config/nvim/plugged/vim-snippets/snippets/"`. Everything seems to work besides the interpolation.

edit: I have also noticed this behavior in vim. I also noticed that you cannot `:set compatible` in neovim, so I tried vim and `:set compatible` and I got the same error.

Hopefully, you can help solve this.

Thanks

**Comment by dylnmc** [comment]
not sure how I didn't try this

snippet le "last edit"
	# last edited: `strftime("%c")`

I looked in snippets.snippets because I accidentally did `date<tab>` and it completed and pasted the date yet wasn't in py.snippets. Did I misread the documentation? If so sorry about the issue.
