### ISSUE TITLE
javascript error node.js

### ISSUE THREAD

**Issue by pashashocky** [SirVer/ultisnips#768]
hello i have the following error when trying to edit .js files: 

```
Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/user/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line 'mi - BEM mix mod' in .vim/bundle/vim-snippets/snippets/javascript/bemjson.snippets:45
```

would be great if someone could help please

**Comment by pashashocky** [comment]
Seems it was just a comment that has not been commented out properly. probably needs a fix :) 
.vim/bundle/vim-snippets/snippets/javascript/bemjson.snippets:45
