### ISSUE TITLE
Undoing snippet throws an error

### ISSUE THREAD

**Issue by purpleP** [SirVer/ultisnips#800]
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 342, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 295, in _update
    ct = self.current_text
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
    return _vim.buf[self._start.line][self._start.col:self._end.col]
  File "/home/michael/.vim/plugged/ultisnips/pythonx/UltiSnips/_vim.py", line 25, in __getitem__
    rv = vim.current.buffer[idx]
  File "/home/michael/code/moex/issplus/.venv/lib/python3.5/site-packages/neovim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/home/michael/code/moex/issplus/.venv/lib/python3.5/site-packages/neovim/api/common.py", line 41, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/michael/code/moex/issplus/.venv/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/michael/code/moex/issplus/.venv/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Index out of bounds'

```
In case gif is to big here's a [video](https://youtu.be/ycCRzoIPBMY)
![out](https://cloud.githubusercontent.com/assets/6205841/20885553/e970c42e-bb0a-11e6-8bf7-4a3d0430683e.gif)

**Comment by SirVer** [comment]
Can't repro at 43b059bf1c20a1d328b7499c45332d367620c541. Might be because I do not have the exact snippet definitions that are used in this video or the bug has since been fixed. 

Closing as cant repro.
