### ISSUE TITLE
list index out of range after selection from UltiSnipsListSnippets

### ISSUE THREAD

**Issue by kayfay** [SirVer/ultisnips#837]
I enter date, call for UltiSnipsListSnippets, then select 2 and this error message appears.

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/atools/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/atools/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 204, in list_snippets
    snippet = _ask_snippets(snippets)
  File "/home/atools/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 53, in _ask_snippets
    return _ask_user(snippets, display)
  File "/home/atools/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 39, in _ask_user
    return a[rv - 1]
IndexError: list index out of range

**Comment by SirVer** [comment]
Cannot repro. Very likely recently fixed. Please speak up if this is still happening for you.
