### ISSUE TITLE
Split window with error message on keypress in Vim insert mode

### ISSUE THREAD

**Issue by schoettl** [SirVer/ultisnips#847]
I'm suddenly getting this error when pressing any key in Vim insert mode in an file of filetype org (Orgmode).

I'm on Arch, Vim 8.0, Python 3.6.0.
I just upgraded all Vim plugins, same error.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet_manager.py", line 856, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet_manager.py", line 702, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet/source/file/_base.py", line 92, in _parse_snippets
    self._file_hashes[filename] = _hash_file(filename)
  File "/home/jakob/.cache/dein/.cache/init.vim/.dein/pythonx/UltiSnips/snippet/source/file/_base.py", line 19, in _hash_file
    return hashlib.sha1(open(path, 'rb').read()).hexdigest()
AttributeError: 'module' object has no attribute 'sha1'
```

Any ideas? Thank you.

**Comment by SirVer** [comment]
can't repro. Probably stale. Closing, please file a new issue if this is still the case.
