### ISSUE TITLE
Using vim to open nixpgks .nix file causes errors:

### ISSUE THREAD

**Issue by wpoosanguansit** [SirVer/ultisnips#852]
I do have ultisnips plugin configured and working correct for haskell and purescript files (at the least).  But it fails when I tried to open a .nix file.  There is no snippet for .nix file defined.  Below is the output:

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    file_data = compatibility.open_ascii_file(filename, 'r').read()
  File "/nix/store/f9mdk7k6kbc3mjhwdhaj6jp3iwlcc00z-vimplugin-vim-ultisnips/share/vim-plugins/vim-ultisnips/pythonx/UltiSnips/compatibility.py", line 76, in open_ascii_file
    return open(filename, mode)
IOError: [Errno 21] Is a directory: '/nix/store'

Thanks.

**Comment by andreyorst** [comment]
Can you please attach some `.nix` file? Are you using some kind of plugin to support `.nix` filetype? Vim don't detects this filetype out of the box. 

I can't reproduce it by opening empty `test.nix`, and running `date` or `datetime` snippets.
![image](https://user-images.githubusercontent.com/19470159/38660201-18f50e86-3e35-11e8-822e-7543bb941ccb.png)

**Comment by wpoosanguansit** [comment]
I am sorry that this just slipped off my plate last week.  I have attaced the

[shell.txt](https://github.com/SirVer/ultisnips/files/1934652/shell.txt)

I do have the plug in for nix enabled at some point.  i am not entirely sure if that would cause anything.  thanks.

**Comment by andreyorst** [comment]
With just plain setup of ultisnips i can't reproduce the problem. Can you please provide a docker container accordingly to [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)

**Comment by wpoosanguansit** [comment]
Hi, I am sorry for the late reply.  I really love to help by making an image but, unfortunately, I have moved to NeoVim in the past two months.  And I didn't really have the nix plugin installed anymore.  So I am not really sure how to reproduce that for you in this case.  
    On Sunday, April 22, 2018, 12:13:32 PM PDT, Andrey Orst <notifications@github.com> wrote:  
 
 
With just plain setup of ultisnips i can't reproduce the problem. Can you please provide a docker container accordingly to CONTRIBUTING.md#reproducing-bugs
