### ISSUE TITLE
UltiSnips + YouCompleteMe (and other plugins) makes vimgrep slow 

### ISSUE THREAD

**Issue by ColinKennedy** [SirVer/ultisnips#853]
I've recently started using vimgrep more in my workflow and discovered that it is pretty slow compared to other search options. I narrowed down the issue to UltiSnips + other plugins / extensions. One of the biggest problems seemed to be UltiSnips + YouCompleteMe

Here are two profile logs, both have UltiSnips enabled and the second has YouCompleteMe disabled

With YCM Enabled

`
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 2470  26.004598   2.333635  <SNR>45_OnBufferRead()
 1892  21.406827             UltiSnips#SnippetsInCurrentScope()
 1892   1.945219   1.926670  <SNR>45_OnFileReadyToParse()
    2   0.197265   0.031363  gzip#read()
 2476   0.102082   0.017048  <SNR>45_AllowedToCompleteInCurrentBuffer()
 2470   0.099352             <SNR>45_DisableOnLargeFile()
 2515   0.086037             <SNR>45_AllowedToCompleteInBuffer()
 1892   0.050976             <SNR>45_SetUpCompleteopt()
   39   0.042619   0.041616  <SNR>45_OnBufferUnload()
 4362   0.040426             <SNR>45_SetUpYcmChangedTick()
 2467   0.035975             SetNumberRelative()
    1   0.027071             zip#Browse()
 1892   0.011542             <SNR>45_SetCompleteFunc()
   67   0.005516             <SNR>6_FTheader()
   18   0.005480   0.002507  SetFileTypeSH()
   83   0.003948             <SNR>6_ProtoCheck()
  113   0.003447             <SNR>6_FTlpc()
   19   0.002973             SetFileTypeShell()
    2   0.002006             <SNR>6_FTidl()
    1   0.002005             <SNR>6_FTxml()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
 1892             21.406827  UltiSnips#SnippetsInCurrentScope()
 2470  26.004598   2.333635  <SNR>45_OnBufferRead()
 1892   1.945219   1.926670  <SNR>45_OnFileReadyToParse()
 2470              0.099352  <SNR>45_DisableOnLargeFile()
 2515              0.086037  <SNR>45_AllowedToCompleteInBuffer()
 1892              0.050976  <SNR>45_SetUpCompleteopt()
   39   0.042619   0.041616  <SNR>45_OnBufferUnload()
 4362              0.040426  <SNR>45_SetUpYcmChangedTick()
 2467              0.035975  SetNumberRelative()
    2   0.197265   0.031363  gzip#read()
    1              0.027071  zip#Browse()
 2476   0.102082   0.017048  <SNR>45_AllowedToCompleteInCurrentBuffer()
 1892              0.011542  <SNR>45_SetCompleteFunc()
   67              0.005516  <SNR>6_FTheader()
   83              0.003948  <SNR>6_ProtoCheck()
  113              0.003447  <SNR>6_FTlpc()
   19              0.002973  SetFileTypeShell()
   18   0.005480   0.002507  SetFileTypeSH()
    2              0.002006  <SNR>6_FTidl()
    1              0.002005  <SNR>6_FTxml()
`

With YCM disabled

`
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    2   0.096545   0.021645  gzip#read()
    1   0.026893             zip#Browse()
 2467   0.025100             SetNumberRelative()
   18   0.005546   0.002541  SetFileTypeSH()
   83   0.003009             <SNR>6_ProtoCheck()
   19   0.003005             SetFileTypeShell()
   67   0.003002             <SNR>6_FTheader()
    1   0.002005             <SNR>6_FTxml()
    1   0.001505             <SNR>8_LoadFTPlugin()
    2   0.001505             <SNR>6_FTidl()
  113   0.001504             <SNR>6_FTlpc()
    3   0.001502   0.000502  <SNR>6_FTasm()
   24   0.001002             <SNR>6_StarSetf()
    1   0.001002             <SNR>4_SynSet()
    3   0.001000             <SNR>6_FTasmsyntax()
    6   0.000503             <SNR>6_FTpl()
    1   0.000502             <SNR>11_BMTruncName()
    1   0.000502   0.000000  <SNR>11_BMFilename()
    1   0.000502   0.000000  <SNR>11_BMAdd()
    1   0.000502   0.000000  <SNR>11_BMMunge()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1              0.026893  zip#Browse()
 2467              0.025100  SetNumberRelative()
    2   0.096545   0.021645  gzip#read()
   83              0.003009  <SNR>6_ProtoCheck()
   19              0.003005  SetFileTypeShell()
   67              0.003002  <SNR>6_FTheader()
   18   0.005546   0.002541  SetFileTypeSH()
    1              0.002005  <SNR>6_FTxml()
    1              0.001505  <SNR>8_LoadFTPlugin()
    2              0.001505  <SNR>6_FTidl()
  113              0.001504  <SNR>6_FTlpc()
   24              0.001002  <SNR>6_StarSetf()
    1              0.001002  <SNR>4_SynSet()
    3              0.001000  <SNR>6_FTasmsyntax()
    6              0.000503  <SNR>6_FTpl()
    3   0.001502   0.000502  <SNR>6_FTasm()
    1              0.000502  <SNR>11_BMTruncName()
    1              0.000501  <SNR>9_LoadIndent()
    1   0.000502   0.000000  <SNR>11_BMFilename()
    1   0.000502   0.000000  <SNR>11_BMAdd()
`
So the difference in speed is quite high. YCM isn't the only plugin where this seems to happen, too, but I haven't narrowed down the others, yet.

Just for reference, in both search cases, I ran this command on Vim version 7.4's unzipped source directory (ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2)

**Comment by ColinKennedy** [comment]
#827

**Comment by seletskiy** [comment]
@ColinKennedy: Can you try branch https://github.com/SirVer/ultisnips/tree/optimize-snippets-in-current-scope?

**Comment by ColinKennedy** [comment]
Hi @seletskiy I tried that branch out but my results were pretty much unaffected and in some cases produced errors in Python files because of my .py snippets.

+----------+-------------------------+---------+
| With YCM | With UltiSnips Snippets |  Time   |
+----------+-------------------------+---------+
| No       | Yes                     | 16.14 s |
| Yes      | Yes                     | 82.16 s |
| Yes      | No                      | 82.46 s |
| No       | No                      | 10.76 s |
+----------+-------------------------+---------+

The reason why I included with and without ultisnips snippets is because I received this error in my python.snippets:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/sting/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/sting/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 189, in snippets_in_current_scope
    "let g:current_ulti_dict = {" + ','.join(dict_definition) + '}'
  File "/home/sting/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in command
    return as_unicode(vim.command(as_vimencoding(cmd)))
error: Vim(let):E721: Duplicate key in Dictionary: "currentdir"
```

currentdir is one of two snippet triggers that I use. 

```
snippet currentdir "Gets the current directory, in Python" b
CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
endsnippet 


snippet currentdir "Gets the current directory, in Python"
os.path.dirname(os.path.realpath(__file__))
endsnippet 
```

After removing those duplicate snippet triggers and others like it, the errors went away but the time taken to do the search remained roughly the same.

Lastly, in between the time we talked, I discovered that `set eventignore=all` makes vimgrep run quickly even with everything enabled. It's likely that SnippetInCurrentScope is running on each file as it's being read, which is causing the slowdown. I tried running set verbose=9 to see which autocmd was specifically causing it to trigger but the log was enormous. Will try again with lower levels tomorrow.

Anyway, my current solution is to just store eventignore before the search, set to =all, do vimgrep and restore it after and then `e!` the file so UltiSnips doesn't break. That said, that solution is definitely not ideal. Please let me know how else I can help / if you need more specific logs.
