### ISSUE TITLE
Error: Vim:E21: Cannot make changes, 'modifiable' is off

### ISSUE THREAD

**Issue by rukbotto** [SirVer/ultisnips#866]
UltiSnips is crashing each time I open a netrw window after using mustache snippets:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 342, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_mirror.py", line 26, in _update
    self.overwrite(self._get_text())
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 132, in overwrite
    self._start, self._end, gtext or self._initial_text)
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 34, in _text_to_vim
    _vim.buf[start.line:end.line + 1] = new_lines
  File "/Users/rukbotto/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 38, in __setslice__
    vim.current.buffer[i:j] = [as_vimencoding(l) for l in text]
error: Vim:E21: Cannot make changes, 'modifiable' is off
```

![ultisnips error](https://user-images.githubusercontent.com/1110747/27711479-109405d6-5ce9-11e7-85a9-dffc779a3574.jpg)

Mustache snippets I'm using:

```
priority 1

snippet {{ "Variable" i
{{ $1 }}$0
endsnippet

snippet {{{ "Raw variable" i
{{{ $1 }}}$0
endsnippet

snippet {{# "Section" i
{{# $1 }}${VISUAL}$2{{/ $1 }}$0
endsnippet

snippet {{^ "Inverted section"
{{^ $1 }}$2{{/ $1 }}$0
endsnippet

snippet {{> "Partial" i
{{> $1 }}$0
endsnippet

snippet {{! "Comment start"
{{! ${VISUAL}$0
endsnippet

snippet !}} "Comment"
{{! ${VISUAL}$1 }}$0
endsnippet
```

**Comment by SirVer** [comment]
The snippets work fine for me. How are you opening the netrw window? Which precise key combination triggers the bug for you?

**Comment by rukbotto** [comment]
I tested today and no error is thrown, mustache snippets and netrw are working fine. Answering your question, I'm using <kbd>-</kbd> key to open netrw.

**Comment by SirVer** [comment]
Awesome, seems like this got fixed then.
