### ISSUE TITLE
Markdown table snippet breaks on various dimensions

### ISSUE THREAD

**Issue by 8bittree** [SirVer/ultisnips#877]
With Vim 8 and Python 2.7.13 on a Mac, the markdown table snippet from [/honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/markdown.snippets) will, when given certain dimensions, throw an error:

>     An error occured. This is either a bug in UltiSnips or a bug in a
>     snippet definition. If you think this is a bug, please report it to
>     https://github.com/SirVer/ultisnips/issues/new.
>
>     Following is the full stack trace:
>     Traceback (most recent call last):
>       File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
>         return func(self, *args, **kwds)
>       File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 232, in expand_anon
>         self._do_snippet(snip, before)
>       File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 689, in _do_snippet
>         self._jump()
>       File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 495, in _jump
>         self._csnippets[0].update_textobjects()
>       File "~/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 85, in update_textobjects
>         'The snippets content did not converge: Check for Cyclic '
>     RuntimeError: The snippets content did not converge: Check for Cyclic dependencies or random strings in your snippet. You can use 'if not snip.c' to make sure to only expand random output once.

This also results in a large number of repetitions of the table dimensions being inserted into the file:

```
 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  | 5x4 |  |  | 
:-|:-|:-|:-
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  | 
```
I have not noticed a cohesive pattern, but a few of the dimensions it has occurred for are 5x4, 11x3, 32x3, 64x3, 2x3, 2x5, and 6x5.

It does not seem to be entirely consistent. With the 2x5, for example, it seems to throw an error only every other time and work just fine every other time.

The snippet in question is:

```
global !p
def create_table(snip):
    # retrieving single line from current string and treat it like tabstops count
    placeholders_string = snip.buffer[snip.line].strip().split("x",1)
    rows_amount = int(placeholders_string[0])
    columns_amount = int(placeholders_string[1])

    # erase current line
    snip.buffer[snip.line] = ''

    # create anonymous snippet with expected content and number of tabstops
    anon_snippet_title = ' | '.join(['$' + str(col) for col in range(1,columns_amount+1)]) + "\n"
    anon_snippet_delimiter = ':-|' * (columns_amount-1) + ":-\n"
    anon_snippet_body = ""
    for row in range(1,rows_amount+1):
        anon_snippet_body += ' | '.join(['$' + str(row*columns_amount+col) for col in range(1,columns_amount+1)]) + "\n"
    anon_snippet_table = anon_snippet_title + anon_snippet_delimiter + anon_snippet_body

    # expand anonymous snippet
    snip.expand_anon(anon_snippet_table)
endglobal

post_jump "create_table(snip)"
snippet "tb(\d+x\d+)" "Customizable table" br
`!p snip.rv = match.group(1)`
endsnippet
```

**Comment by seletskiy** [comment]
Try to avoid using python interpolation in the body of the snippet, because it's immediately replaced my `post_jump` code. I guess that's causing snippet engine to behave wrong.

E.g., properly snippet can be modified to use `pre_expand` to work correctly:

```
```

**Comment by 8bittree** [comment]
That seems to work, thanks. I've opened a [pull request](https://github.com/honza/vim-snippets/pull/958) over on the honza/vim-snippets with your recommended fix.
