### ISSUE TITLE
Ultisnips#ExpandTrigger throws error

### ISSUE THREAD

**Issue by purpleP** [SirVer/ultisnips#884]
Not sure this log is helpful. But it should be easy to reproduce
`inoremap <silent> <expr> <C-j> UltiSnips#ExpandSnippet()`

However with `g:UltiSnipsExpandTrigger = '<C-j>' is working properly. Seems like a bug.

```

    self.instantiate(snippet_instance, initial_text, indent)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/snippet/definition/ultisnips.py", line 15, in instantiate
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    return parse_and_instantiate(snippet_instance, initial_text, indent)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/snippet/parsing/ultisnips.py", line 50, in parse_and_instantiate
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    finalize(all_tokens, seen_ts, parent_to)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/snippet/parsing/_base.py", line 68, in finalize
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    snippet_instance.replace_initial_text()
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 49, in replace_initial_text
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    _place_initial_text(self)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 45, in _place_initial_text
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    obj.overwrite()
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 132, in overwrite
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    self._start, self._end, gtext or self._initial_text)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 34, in _text_to_vim
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    _vim.buf[start.line:end.line + 1] = new_lines
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/_vim.py", line 34, in __setitem__
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    return self.__setslice__(idx.start, idx.stop, text)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/_vim.py", line 38, in __setslice__
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    vim.current.buffer[i:j] = [as_vimencoding(l) for l in text]
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/api/buffer.py", line 65, in __setitem__
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    return self.request('buffer_set_lines', start, end, False, lines)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    return self._session.request(name, self, *args, **kwargs)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    res = self._session.request(name, *args, **kwargs)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    raise self.error_wrapper(err)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
neovim.api.nvim.NvimError: b'Vim:E523: Not allowed here'
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
During handling of the above exception, another exception occurred:
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "<string>", line 1, in <module>
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 50, in wrapper
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    _vim.new_scratch_buffer(msg)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.config/nvim/pack/packages/opt/ultisnips/pythonx/UltiSnips/_vim.py", line 157, in new_scratch_buffer
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    vim.command('botright new')
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/api/nvim.py", line 218, in command
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    return self.request('nvim_command', string, **kwargs)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    res = self._session.request(name, *args, **kwargs)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
  File "/home/michael/.venv/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
    raise self.error_wrapper(err)
Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:

Error detected while processing function UltiSnips#ExpandSnippet[1]..provider#python3#Call:
line   18:
neovim.api.nvim.NvimError: b'Vim(new):E523: Not allowed here'
```

**Comment by purpleP** [comment]
Hmm, seems like `inoremap <silent> ... <CR>=UltiSnips#ExpandTrigger()<CR>` works
