### ISSUE TITLE
Traceback upon import from vimsnippets

### ISSUE THREAD

**Issue by x1o** [SirVer/ultisnips#894]
Hi, I've installed UltiSnips on Windows. I'm getting this traceback upon trying to expand one of the standard snippets (from all.snippets, I believe):

```
Following is the full stack trace:

Traceback (most recent call last):
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\snippet_manager.py", line 163, in expand
    if not self._try_expand():
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\snippet_manager.py", line 725, in _try_expand
    self._do_snippet(snippet, before)
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\snippet_manager.py", line 680, in _do_snippet
    None, start, end)
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\snippet\definition\_base.py", line 421, in launch
    snippet_instance.update_textobjects()
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\text_objects\_snippet_instance.py", line 79, in update_textobjects
    if obj._update(done):
  File "<path_to_vim>\vim\vimfiles\bundle\UltiSnips\pythonx\UltiSnips\text_objects\_python_code.py", line 271, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 1, in <module>
ImportError: No module named 'vimsnippets'

Executed snippet code:

  1 > from vimsnippets import foldmarker, make_box, get_comment_format
```

Python 3 "embeddable" is used. PATH points to its installation location, and the rest of the plugin's functionality is working fine, except for this little thing.

**Comment by SirVer** [comment]
My hunch is that the pythonx directory of vimsnippets is not correctly found, no idea why though.

Please post a minimal vimrc reproducing the issue and we'll reopen.

**Comment by zenAndroid** [comment]
I have a different OS(Linux Mint 18.3 Sylvia) but basically same issue, i went to the Ultisnips pythonx directory and looked around in all of the *.py files and found no mention of vimsnippets, nor any file named vimsnippets, weird.

Thank you for the plugin by the way :+1:

**Comment by beardnick** [comment]
Hi, I encountered to this problem rencently. Finnally, I found it that the vimsnippets module was from honza/vim-snippets and I just copied the snippets without downloading the full plugin. You may sovle this problem by installing the honza/vim-snippets plugin.
