### ISSUE TITLE
Some bugs on neovim

### ISSUE THREAD

**Issue by rawaludin** [SirVer/ultisnips#901]
I'm using neovim, this error messages sometimes show up when I type:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 46, in ensure
    if self._needs_update(ft):
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 62, in _needs_update
    existing_files = self._get_all_snippet_files_for(ft)
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/snipmate.py", line 119, in _get_all_snippet_files_for
    return snipmate_files_for(ft)
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/snipmate.py", line 46, in snipmate_files_for
    for rtp in _vim.eval('&runtimepath').split(','):
  File "/Users/rahmatawaludin/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
  File "/usr/local/lib/python3.6/site-packages/neovim/plugin/script_host.py", line 183, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Keyboard interrupt'
```

I don't know how to trigger this manually. Is there anything I can do?

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
