### ISSUE TITLE
Can't open tempfile

### ISSUE THREAD

**Issue by mcepl** [SirVer/ultisnips#912]
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/home/matej/.vim/pack/thirdparty/start/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
error: Vim:E484: Can't open file /tmp/veMVq3N/6
```
When trying this snippet:
```
snippet """"""
`!v system("pydocstring -f reST " . expand("%:f") . "'(" . line(".") . ", " . col(".") . "')")`
endsnippet
```
I happily accept the idea, that I am doing something wrong, but this seems like a reasonable thing to do.
[pydocstrnig](https://github.com/robodair/pydocstring) generates [docstrings](https://github.com/Microsoft/vscode-python/issues/62) in Python.

**Comment by mcepl** [comment]
That's actually a good point. Thanks.
