### ISSUE TITLE
UltiSnips python snippets crashing when using with plugin "Python-mode"

### ISSUE THREAD

**Issue by KshitizGIT** [SirVer/ultisnips#922]
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

~~~
Following is the full stack trace:
Traceback (most recent call last):
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
    rv = self._try_expand()
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 440, in launch
    self.instantiate(snippet_instance, initial_text, indent)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/ultisnips.py", line 15, in instantiate
    return parse_and_instantiate(snippet_instance, initial_text, indent)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/parsing/ultisnips.py", line 50, in parse_and_instantiate
    finalize(all_tokens, seen_ts, parent_to)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/parsing/_base.py", line 68, in finalize
    snippet_instance.replace_initial_text()
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 49, in replace_initial_text
    _place_initial_text(self)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 45, in _place_initial_text
    obj.overwrite()
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 132, in overwrite
    self._start, self._end, gtext or self._initial_text)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 34, in _text_to_vim
    _vim.buf[start.line:end.line + 1] = new_lines
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 34, in __setitem__
    return self.__setslice__(idx.start, idx.stop, text)
  File "/home/kshitiz/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 38, in __setslice__
    vim.current.buffer[i:j] = [as_vimencoding(l) for l in text]
vim.error: Vim:E315: ml_get: invalid lnum: 22
~~~

This is occuring for the class snippet ..

**Comment by andreyorst** [comment]
Can you please provide a docker repo? You didn't mentioned any useful info except traceback wich is good, but not enough. What is your vim version, ultisnips version or commit, python mode plugin version, etc etc. Please see [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)
