### ISSUE TITLE
Error on triggering UltiSnips snippet

### ISSUE THREAD

**Issue by gambledor** [SirVer/ultisnips#940]
OS: Archlinux
Python version 3.6

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File ".config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_python_code.py", line 308, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.6/posixpath.py", line 448, in relpath
    raise ValueError("no path specified")
ValueError: no path specified

Executed snippet code:
  1
  2   relpath = os.path.relpath(path)
  3   m = re.search(r'[A-Z].+(?=/)', relpath)
  4   if m:
  5       snip.rv = m.group().replace('/', '\\')
  6

**Comment by SirVer** [comment]
@gambledor You did not post your snippet in context, but `raise ValueError("no path specified")` leads me to believe that in your 2nd line, `path = None`. So this is an error in your snippet.
