### ISSUE TITLE
Autocommand in vimrc interfers with ultisnips

### ISSUE THREAD

**Issue by kiryph** [SirVer/ultisnips#946]
I get following error
```
vim.error: Vim(autocmd):E216: No such event: unite call UltiSnips#LeavingBuffer()
```

minimal vimrc using [minpac](https://github.com/k-takata/minpac) as my package manager:
```viml
set pythonthreehome=/usr/local/Frameworks/Python.framework/Versions/3.6

let g:UltiSnipsUsePythonVersion = 3

packadd minpac
call minpac#init()
call minpac#add('SirVer/ultisnips')
call minpac#add('honza/vim-snippets')

function! ExpandSnippetOrJumpForwardOrReturnTab()
	let snippet = UltiSnips#ExpandSnippetOrJump()
	if g:ulti_expand_or_jump_res > 0
	    return snippet
	else
	    return "\<TAB>"
	endif
endfunction
inoremap <silent> <expr> <TAB>
	\ pumvisible() ? "\<C-n>" :
	\ "<C-R>=ExpandSnippetOrJumpForwardOrReturnTab()<CR>"

filetype plugin indent on
syntax enable

" Remove this autocommand to resolve issue
augroup Filetype
  autocmd!
  autocmd BufNewFile,BufRead .gv setfiletype dot
augroup END
```
Trigger simple snippet `box` from https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets

Full error message:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
    if not self._try_expand():
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 624, in _do_snippet
    self._setup_inner_state()
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 376, in _setup_inner_state
    _vim.command('autocmd Filetype unite call UltiSnips#LeavingBuffer()')
  File "/Users/kiryph/.vim/pack/minpac/start/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in command
    return as_unicode(vim.command(as_vimencoding(cmd)))
vim.error: Vim(autocmd):E216: No such event: unite call UltiSnips#LeavingBuffer()
```

Vim Version: MacVim snapshot 146 from https://github.com/macvim-dev/macvim/releases

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 24 2018 08:30:22)
macOS version
Included patches: 1-1633
Compiled by travis@Traviss-Mac-913.local
Huge version with MacVim GUI.  Features included (+) or not (-):   
```

**Comment by kiryph** [comment]
I have figured it out: You should not use event names for your name of an augroup. Read last sentence of `:help :augroup`:

```
							*:aug* *:augroup*
:aug[roup] {name}		Define the autocmd group name for the
				following ":autocmd" commands.  The name "end"
				or "END" selects the default group.
				**To avoid confusion, the name should be
				different from existing {event} names, as this
				most likely will not do what you intended.**
```
